### ISSUE TITLE
-fno-reorder-blocks-and-partition make gcc8 compile slow

### ISSUE THREAD

**Issue by zpget** [facebookincubator/BOLT#105]
gcc 8 compile with -fno-reorder-blocks-and-partition problem
1. add -fno-reorder-blocks-and-partition flag need 18 minutes, trans get no error
2. no -fno-reorder-blocks-and-partition flag only need 6 minutes
    but get BinaryFunction.cpp:4169: llvm::bolt::DebugAddressRangesVector llvm::bolt::BinaryFunction::getOutputAddressRanges() const: Assertion `!Frag->isSimple() && "fragment of non-simple function should also be non-simple"' failed
 how to fix writing debug info fail?

**Comment by zpget** [comment]
> The fact that it takes 3X with `-fno-reorder-blocks-and-partition` is surprising. We are working on adding a full support for `-f-reorder-blocks-and-partition` on input. Stay tuned.

thanks, and when can use the support for `-f-reorder-blocks-and-partition` ?

**Comment by rafaelauler** [comment]
Closing since this is duplicated with issue #57
