### ISSUE TITLE
Is ReorderData pass is wrong?

### ISSUE THREAD

**Issue by yota9** [facebookincubator/BOLT#113]
Hello!
I'm looking at ReorderData pass currently and I don't understand one moment. 
For example if we are reordering data at .rodata section we might have a situation, when other section (for example .data) has an absolute address stored of some .rodata field. When we move data in .rodata  section the address of the object could obviously change, but as I see the only relocations that are fixed are in changed section, but not in other ones. Should not we look through the all relocations of other sections that could  point to the data of changed section and fix them too (or probably store all referenced relocations to BinaryData)? Or don't run this pass with BC.HasReolcations?
Thank you!

**Comment by maksfb** [comment]
Yes, you are right, we have to track all relocations. I haven't looked at this pass in a while as it was an experimental work. Did you find out that the relocations were updated or you closed the task for other reasons?

**Comment by yota9** [comment]
@maksfb I've found out that I was probably wrong :)  As far as I understand the relocations are probably handled by emitAsData()->emit() since the symbol address is changed.
The one problem I've found is relative relocations handling, patchELFAllocatableRelaSections only handles binary functions, but not binary data, but it was easy to fix :) Thank you!
