### ISSUE TITLE
If the collection of a profile with branches is not available, how can I improve the performance of BOLT.

### ISSUE THREAD

**Issue by fengdongsheng** [facebookincubator/BOLT#114]
[this](https://github.com/facebookincubator/BOLT/blob/master/README.md) link says ：If the collection of a profile with branches is not available，the quality of the profile information would not be as good, and performance gains with BOLT are expected to be lower.

I'd like to ask if there are other ways to improve the performance of the bolt in this case。

**Comment by maksfb** [comment]
Yes. Give a try to instrumentation described further down the README: ["With instrumentation (experimental)."
](https://github.com/facebookincubator/BOLT/blob/master/README.md#with-instrumentation-experimental)
