### ISSUE TITLE
First release?

### ISSUE THREAD

**Issue by kloczek** [facebookincubator/BOLT#119]
Is it possible to tag first release?

**Comment by rafaelauler** [comment]
Usually our trunk is the release or close to be released.

**Comment by kloczek** [comment]
Nevertheless verion tags would be usefull on packaging and tracking some milestone changes of the BOLT :)

**Comment by rafaelauler** [comment]
Sounds good, I added the first release.

**Comment by kloczek** [comment]
Thank you :)

I'm closing that ticket.
