### ISSUE TITLE
Unable to build llvm-bolt with error : ninja: build stopped: subcommand failed

### ISSUE THREAD

**Issue by nmdis1999** [facebookincubator/BOLT#120]
Hello,
I am very new with BOLT, I am trying to build it with manual commands. However, while building 
```
> cd ..
> mkdir build
> cd build
> cmake -G Ninja ../llvm -DLLVM_TARGETS_TO_BUILD="X86;AArch64" -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON
> ninja
```

results in following error: ninja: build stopped: subcommand failed.
I tried using fewer thread, but not sure how to fix it.
[CMakeError.log](https://gist.github.com/nmdis1999/1a2af56eae51a57ccb1f42e2d74f66de)

**Comment by rafaelauler** [comment]
Thanks for trying BOLT, it looks like your system compiler is having issues being able to build C++ programs. I would start by checking LLVM's recommendation on software prerequisites:

https://llvm.org/docs/GettingStarted.html#software

BOLT heavily relies on LLVM and is written using the same coding standards. BOLT uses an LLVM version from about 2 years ago and we are in the process of rebasing it to use the most recent LLVM, but the software requirements from current LLVM should still be fine to build BOLT.

**Comment by aaupov** [comment]
@nmdis1999: I think you've been able to resolve the system compiler issue, right? Can we close this issue?

**Comment by nmdis1999** [comment]
Yes, closing the issue. Thanks for the help :)
