### ISSUE TITLE
[Instrumentation] Failed to extract jump table base

### ISSUE THREAD

**Issue by kmod** [facebookincubator/BOLT#126]
I'm getting this error when instrumenting our binary, depending on which compiler we used:

```
$ ../../bolt/build/bin/llvm-bolt pyston -instrument -o pyston.bolt_inst
BOLT-INFO: Target architecture: x86_64
BOLT-INFO: BOLT version: f137ed238db11440f03083b1c88b7ffc0f4af65e
BOLT-INFO: first alloc address is 0x400000
BOLT-INFO: creating new program header table at address 0xa00000, offset 0x600000
BOLT-INFO: enabling relocation mode
BOLT-INFO: enabling -align-macro-fusion=all since no profile was specified
Failed to extract jump table base
UNREACHABLE executed at BinaryFunction.cpp:3782!
```
[pyston.zip](https://github.com/facebookincubator/BOLT/files/6104857/pyston.zip)

**Comment by kmod** [comment]
If it's a lot easier maybe it could just abort dealing with functions with jumptables that can't be extracted?  Right now the workaround we've found is to use -jump-tables=none which is pretty broad.

**Comment by rafaelauler** [comment]
Thanks for the repro! I will try here.

Regarding workarounds, what we usually do with partially supported binaries is to use -skip-funcs=

For example, if BOLT is having issues with just one function or a small set of functions, you can use -skip-funcs=funcname or you can use a wildcard too, such as -skip-funcs=myfunc*

In the case of instrumentation, though, it will not generate profile for these functions.

**Comment by rafaelauler** [comment]
I confirmed the bug. Notice that BOLT should still be able to process this function -- the bug is in the instrumentation pass. You can also workaround this by using sampled profile with Linux perf

**Comment by kmod** [comment]
Oh great to know about the -skip-funcs flag, that's a big help thanks!

**Comment by kmod** [comment]
Thanks everyone!
