### ISSUE TITLE
Expand auto types

### ISSUE THREAD

**Issue by MaskRay** [facebookincubator/BOLT#130]
https://llvm.org/docs/CodingStandards.html#use-auto-type-deduction-to-make-code-more-readable `auto` appears to be aggressively used. The code should be refactored before dropping into the upstream.

**Comment by steveire** [comment]
Note that at least flang and mlir use `auto` a lot too, so there is plenty of precedent for using it both inside and outside llvm. Any implication in the coding standard that `auto` shouldn't be used normally is probably just out of date.

**Comment by aaupov** [comment]
@MaskRay, we've revisited the use of `auto` in the codebase and reduced it to lambdas, iterators, template-derived types, places where type is explicitly given in the context, and alias variables. There might still be some places with `auto` where changing it to the expected type changed the binary, so we've left them out.
Commit 684c48d60863d4712b497f8b51ba04421f64ebc8
