### ISSUE TITLE
Does the BOLT support aarch64?

### ISSUE THREAD

**Issue by ijinma** [facebookincubator/BOLT#131]
hi，

I want to use BOLT to run and optimize some programs on my aarch64, but there seems to be [some issues](https://github.com/facebookincubator/BOLT/issues/102), will aarch64 be supported in the future? 

thanks，
ijinma

**Comment by maksfb** [comment]
Even though I'm personally focused on x86-64, I know AArch64 is under [active development](https://github.com/facebookincubator/BOLT/pull/103). I can see it picking up more traction with the upcoming integration with LLVM monorepo.
