### ISSUE TITLE
Split runtime test into separate directories?

### ISSUE THREAD

**Issue by MaskRay** [facebookincubator/BOLT#132]
Some tests run the instrumented executable:

```asm
# From test/X86/instrumentation-dup-jts.s
# RUN: %t.instrumented 120
```

In llvm-project, such runtime tests are in separate directory (e.g. `compiler-rt/test/*`). The generic test should run on most supported OSes (with a few exception of `UNSUPPORTED: system-*`) and most targets (with a few exception of `UNSUPPORTED: $arch`).

**Comment by aaupov** [comment]
Done with this commit: 0958ff46569f4a29a77fad4972a871f15640ac49.
Excluding unsupported OSes is TBD
