### ISSUE TITLE
Large binary file generated by llvm-bolt

### ISSUE THREAD

**Issue by dizhizhou** [facebookincubator/BOLT#138]
Observe a large binary exec file generated by applying llvm-bolt against instrumented bin.

Test code:
```
// simple.c
int main()
{
    return 0;
}
```

Steps:
gcc -Wl,-emit-relocs -no-pie simple.c -o simple  
llvm-bolt simple -instrument -o simple-instrument
./simple-instrument
llvm-bolt simple -o simple.bolt -data=/tmp/prof.fdata  -dyno-stats

ls -l simple
-rwxr-xr-x 1 root root 9192 Apr 12 15:47 simple
ls -l simple.bolt
-rwxr-xr-x 1 root root 6296960 Apr 12 15:49 simple.bolt

simple.bolt is 1000 times larger than the original file.

'readelf -WS simple.bolt' shows that the size is caused by the large offset for .text section.
```
[Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
[24] .text             PROGBITS        0000000000a00000 600000 000167 00  AX  0   0 2097152
```

Can anyone explain why the .text offset is set to such a large number? Is there any option which can reduce the size?

**Comment by rafaelauler** [comment]
That's because BOLT aligns all code that is presumed hot in a 2MB page boundary. See the option -align-text to change this behavior.

**Comment by dizhizhou** [comment]
Which option?
```
llvm-bolt -help | grep align
  -align-blocks                                        - align basic blocks
  -align-functions=<uint>                              - align functions at a given value (relocation mode)
  -align-functions-max-bytes=<uint>                    - maximum number of bytes to use to align functions
  -block-alignment=<uint>                              - boundary to use for alignment of basic blocks
  -preserve-blocks-alignment                           - try to preserve basic block alignment
  -use-compact-aligner                                 - Use compact approach for aligning functions
  -x86-align-branch-boundary-hot-only                  - only apply branch boundary alignment in hot code
  -align-macro-fusion                                  - fix instruction alignment for macro-fusion (x86 relocation mode)
    =none                                              -   do not insert alignment no-ops for macro-fusion
    =hot                                               -   only insert alignment no-ops on hot execution paths (default)
    =all                                               -   always align instructions to allow macro-fusion
```

**Comment by maksfb** [comment]
You can reduce the file size increase by specifying `-no-huge-pages` option. However, you'll get at least 2MB increase due to reasons described at https://github.com/facebookincubator/BOLT/blob/master/src/RewriteInstance.cpp#L612.

**Comment by dizhizhou** [comment]
@maksfb @rafaelauler Are "align-text" and "-huge-pages" options recently added? They are not in the 'llvm-bolt -h' list.

**Comment by dizhizhou** [comment]
@maksfb Thanks.

**Comment by rafaelauler** [comment]
@dizhizhou They are available under --help-hidden

**Comment by dizhizhou** [comment]
> @dizhizhou They are available under --help-hidden

Yep. I just found it after I posted that question:)
