### ISSUE TITLE
ut in rebase code failed

### ISSUE THREAD

**Issue by dongAxis** [facebookincubator/BOLT#140]
hello, 

    I just use the rebase code of bolt.
    But unluckily, X86/debugTypesBug.s just failed.

    It is right or not?

Best Regards
Yifeng

**Comment by ayermolo** [comment]
Hi.

Can you provide more details please.
I just tried locally with our internal branch and the test passed.

Alex

**Comment by rafaelauler** [comment]
Try again, it should work.
