### ISSUE TITLE
[Question] Differentiate a BinaryFunction coming from library?

### ISSUE THREAD

**Issue by Sameeranjoshi** [facebookincubator/BOLT#159]
I am trying to check for a given `BinaryFunction *BF`  if it comes from a library or is it from the same translation unit.
How do we check that?

I am trying to skip the library functions as there is a strong possibility that the libraries may not be compiled with `-g` and I want some information based on debug information.
Thanks.

**Comment by rafaelauler** [comment]
From the perspective of BOLT, there is no difference if a function comes from a library or not. Perhaps you could try to read STT_FILE entries in the symbol table to read the source file name and then associate symbols coming from that file name as a potential problem, but that would be very unreliable.

If you want to skip functions with no debug info, that could be easier to check.
