### ISSUE TITLE
glog failed to symbolize for an address due to anonymously mmapped `.text` section

### ISSUE THREAD

**Issue by KSSysLab** [facebookincubator/BOLT#161]
The glog backtrace printed with unknown symbols.

```
*** Aborted at 1622099628 (unix time) try "date -d @1622099628" if you are using GNU date ***
PC: @          0x792bc90 (unknown)
*** SIGSEGV (@0x1f90) received by PID 43184 (TID 0x7efa77b9f700) from PID 8080; stack trace: ***
    @     0x7f0c0d2bf5e0 (unknown)
    @          0x792bc90 (unknown)
    @          0x792a7fe (unknown)
    @          0x7872853 (unknown)
    @          0x7929cf1 (unknown)
    @          0x79296c0 (unknown)
    @          0x7b1b1a4 (unknown)
    @          0x7a28722 (unknown)
    @          0x7a25e43 (unknown)
    @          0x7a25d37 (unknown)
    @          0x7a25433 (unknown)
    @          0x7a2445d (unknown)
    @          0x7a22d24 (unknown)
    @          0x7a22ad5 (unknown)                                   # <- attention
    @          0x3e11081 grpc::ThreadManager::WorkerThread::Run()    # <- attention
    @          0x3e121cd _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEMN4grpc13ThreadManager12WorkerThreadEFvvEPS9_EEEEEPvSE_
    @     0x7f0c0d2b7e25 start_thread
    @     0x7f0c0cfe534d __clone
```

To symbolize 0x7a22ad5, glog opens the file backing the address by looking up `/proc/self/maps`, parses elf and searches in symbol table and dynamic symbol table.

But `/proc/self/maps` told me 
![image](https://user-images.githubusercontent.com/79680868/119968506-276d8300-bfe0-11eb-9313-384f7ffb4087.png)

0x3e11081 `grpc::ThreadManager::WorkerThread::Run()` belongs to [0x40e000, 0x40bb000) (the second one) whose pathname is the object file while 0x7a22ad5 `(unknown)` belongs to [0x7800000, 0x7e00000) (the last but one) whose pathname is blank which indicates that the memory is anonymously mmapped. [man 5 proc](http://man7.org/linux/man-pages/man5/proc.5.html)

`objdump -h` shows

```
 27 .tm_clone_table 00000000  00000000067ff190  00000000067ff190  063fe190  2**3
                  CONTENTS, ALLOC, LOAD, DATA
 28 .bss          00d3b690  00000000067ff200  00000000067ff200  063fe190  2**7
                  ALLOC
 29 .text         005436cc  0000000007800000  0000000007800000  07400000  2**21
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
 30 .text.cold    00618daf  0000000007d43700  0000000007d43700  07943700  2**6
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
 31 .eh_frame     0085b5e0  000000000835c4b0  000000000835c4b0  07f5c4b0  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
```

0x7a22ad5 is in `.text` section with no doubts.

So glog failed to symbolize 0x7a22ad5 due to the unintended `/proc/self/maps`.

Is it expected? What's wrong with the anonymously mapping `.text` section?

**Comment by KSSysLab** [comment]
addr2line also failed to work.

```
$ addr2line -e a.out 0x3e11081 0x7a22ad5
/tmp/third_party/grpc-v1100/src/cpp/thread_manager/thread_manager.cc:41
??:?
```

**Comment by rafaelauler** [comment]
Thanks for reporting. Interesting, BOLT shouldn't interfere with that unless you are using -hugify option. Are you using it?

If yes, here's the anonymous mmap:
https://github.com/facebookincubator/BOLT/blob/rebased/bolt/runtime/hugify.cpp#L96

That's a technique to request huge pages in older kernels, but now I realize our logic to detect the kernel version shouldn't work outside of facebook, so I guess it is always assuming the kernel does not support madvise.  And I think symbolization is expected to fail if using the anonymous mmap, unless you change the symbolizer in your system to account for that.

On the BOLT side, I think we need to update that logic with a better way to switch between mmap or madvise, and update our documentation on -hugify to explain that the user may lose symbolization if the kernel does not support madvise.

**Comment by KSSysLab** [comment]
Yes, I potentially pass `-hugify` to BOLT. 😅 

> That's a technique to request huge pages in older kernels, but now I realize our logic to detect the kernel version shouldn't work outside of facebook, so I guess it is always assuming the kernel does not support madvise. And I think symbolization is expected to fail if using the anonymous mmap, unless you change the symbolizer in your system to account for that.

Thanks for the detailed explanation. The comment says

``` c++
/// Check whether the kernel supports THP by checking the kernel version.
/// Only fb kernel 5.2 and latter supports it.
```

``` sh
$ cat /sys/kernel/mm/transparent_hugepage/enabled
always [madvise] never
```

Does it mean that I can ignore the `has_pagecache_thp_support()` checking?

**Comment by rafaelauler** [comment]
I think it's fair to assume you can ignore it. I'm not an expert on hugify (I didn't write hugify.cpp), but it looks like we should probably be checking /sys/kernel/mm/transparent_hugepage/enabled instead of checking the kernel version in order to decide whether to use madvise or not.

**Comment by KSSysLab** [comment]
Since it's resolved, so I will close it right now.

**Comment by rafaelauler** [comment]
Thanks. The use of madvise has been addressed in https://github.com/facebookincubator/BOLT/commit/8848491476e04012b125954da50ab970e849d9e6
