### ISSUE TITLE
Fix BOLT layout errors

### ISSUE THREAD

**Issue by rafaelauler** [facebookincubator/BOLT#169]
Some important things changed in our interaction with LLVM's MCStreamer since our last big rebase (branch rebased).

First, JRCXZ out-of-range fixups were intentionally changed to be a an error instead of assertion: https://reviews.llvm.org/D70652  --> converting assertions to errors is always a drama for us because we currently rely on assertions to tell us that something is wrong, instead of checking for errors. This introduced a problem for BOLT because it wouldn't crash anymore when having problems dealing with JRCXZ, but it finishes as if everything succeeded (error code zero). We are currently blacklisting functions with JRCXZ, but ideally, we don't want to proceed if there is any error in layout, and BOLT pre-rebase crashed on *any* such errors (specifically, if MCContext::hadError() returns true).

The fact that this diff in isolation is removing the assertion and converting it into a call to MCContext::reportError() shouldn't be a problem. Prior to the rebase, BOLT would still crash on any calls to reportError() because it was instantiating MCContext without a SourceManager (set to nullptr). reportError() implementation would assert if called without a SourceManager set, and BOLT would crash, and we would have signal that something is odd with our emission. But not anymore. After the rebase, LLVM had a change in MCContext::reportError() code to actually handle the case when SourceManager is null. Now, if MCContext lacks a source manager, it will use an InlineSrcMgr (intended to report errors in inline assembly, where source file is not available). After this important change, BOLT stopped crashing on all reportError() calls, which include another class of errors that we were paying close attention to: "undefined temporary symbols". We definitely do not want to finish with error code zero if we have undefined temporary symbols.

We could easily check if MCContext::hadError() returns true after the final call to finalize MCStreamer in RewriteInstance::emitAndLink() and call exit(1) from BOLT in such case. But changing current rebased BOLT to quit on layout errors causes it to frequently stop working, even in legitimate inputs that used to work before, because of undefined temporary symbols. That's because of another change that still needs to be investigated.

We should make BOLT generate cleaner code to MCStreamer that does not leave symbols undefined -- if we deleted it somehow, we should delete the symbol from MCContext, so MCStreamer isn't lost trying to locate it. If it is intended to be undefined, we should find a way to please MCStreamer just in the way we were doing prior to the rebase. Undefined temp symbols were previously a big signal for us that we were doing something wrong, since we are not supposed to generate undefined symbols when calling our last MCStreamer::finish.

**Comment by maksfb** [comment]
BOLT introduces temp symbols while reading relocations. Later, we may discover that these symbols belong to functions that we will never emit, e.g. cold functions in lite mode. Hence, MCStreamer will not reference those symbols (any existing internal relocations will be ignored), but they will still be part of MCContext. There is no interface to remove symbols from MCContext. When BOLT produces an intermediate .o, the object writer issues these errors as it's iterating over all symbols in the table. Removing temp symbols from MCContext may not be trivial. One possible alternative solution it to emit all undefined temps as dummies forcing them to be defined. They are currently being tracked in `BinaryContext::UndefinedSymbols`.

**Comment by aaupov** [comment]
I think it's addressed in https://reviews.llvm.org/D123263
