### ISSUE TITLE
[Question] Interpretation of multiple files from `-dump-dot-all` .

### ISSUE THREAD

**Issue by Sameeranjoshi** [facebookincubator/BOLT#171]
I was trying to dump the CFG from bolt and was trying to analyze it visually using below command.
`llvm-bolt -dump-dot-all test.clang.out -o test.clang.bolt`

I see too many `*.dot` files generated, while I was trying to analyze what does each file do, I see that there are many files for the same function(`int main` in my binary).
```
 main-00_build-cfg.dot
 main-01_validate-internal-calls.dot
 main-02_strip-rep-ret.dot
'main-12_PLT call optimization.dot'
 main-15_split-functions.dot
 main-16_fix-branches.dot
 main-17_reorder-functions.dot
 main-21_peepholes.dot
 main-22_aligner.dot
 main-23_reorder-data.dot
 main-24_finalize-functions.dot
 main-27_retpoline-insertion.dot
 main-28_assign-sections.dot
 main-29_patch-entries.dot
 main-30_inst-lowering.dot
 main-31_lower-annotations.dot
```

Does this mean the following optimizations passes have run on `main` function?
What do the numbers prefixing the optimization name signify ?
When trying to see what's the different with these files, I see no change in the files(verified using `vimdiff` command), so why too many files?

**Comment by amoksyakov** [comment]
Hello @Sameeranjoshi, as far as I can see in source file BinaryPassManager.cpp:

Does this mean the following optimizations passes have run on main function?
No, the output file name consist of : functionName + PassIdx + PassName. It happens on all functions.

What do the numbers prefixing the optimization name signify ?
it's the key to identify a pass in vector when pass is registered. You can find it into runAllPasses & registerPass.

When trying to see what's the different with these files, I see no change in the files(verified using vimdiff command), so why too many files?
*.dot file contains the stats related to basic blocks.
Can you share the test to reveal a cause?

**Comment by Sameeranjoshi** [comment]
```
#include <stdlib.h>
#include <stdio.h>

#define N 100
#define ITER 100
int main() {

  // output command for documentation:
  int i, k;
  unsigned long c=0;
  unsigned int swap;
  //, a[N], b[N];
  unsigned int *a;
  unsigned int *b;
  a = (unsigned int*) malloc(N*sizeof(unsigned int));
  b = (unsigned int*) malloc(N*sizeof(unsigned int));

  double timex;
  int forward = 1;
  int iterations = ITER;

  for (i=0;i<N;i++)
  {
    a[i] = i;
    b[i] = i;
  }


  for(k=0;k<iterations;k++)
  {
    for (i=0;i<N;i++)
    {
      c += a[i] + b[i] + 3;
      if(i%3 == 0)
      {
        swap = a[i];
        a[i] = b[i];
        b[i]= swap;
      }
      else
      {
        swap = a[i];
        a[i] = b[i]*3;
        b[i]= swap/2;
      }
    }
  }

  printf ("%lu\n", c);
}
```

**Comment by aaupov** [comment]
@Sameeranjoshi:

>Does this mean the following optimizations passes have run on main function?
Yes, it's a pretty standard practice to dump IR/CFG after each pass, for each function that is optimized. Some passes are "technological toolchain" and are applied even when no optimizations are enabled - such as `build-cfg` and `assign-sections`.

>What do the numbers prefixing the optimization name signify ?
It's the pass order.

>When trying to see what's the different with these files, I see no change in the files(verified using vimdiff command), so why too many files?
All files would be identical if for some reason none of the passes changed the input function.
