### ISSUE TITLE
clang-formatting bolt code.

### ISSUE THREAD

**Issue by Sameeranjoshi** [facebookincubator/BOLT#179]
Hello,
I am trying to apply clang-format mentioned as per llvm coding standards at [1].
I see unusual changes to the formatting, is there some clang-format scripts specifically for BOLT?
Here's the unusual change
```
 static cl::opt<bool>
-SrcToInstMap("src-to-inst-map",
-  cl::desc("Build and print source to instructions map"),
-  cl::init(false),
-  cl::ZeroOrMore,
-  cl::cat(AmdAddedOptions));
+    SrcToInstMap("src-to-inst-map",
+                 cl::desc("Build and print source to instructions map"),
+                 cl::init(false), cl::ZeroOrMore, cl::cat(AmdAddedOptions));

```
Is this formatting correct? 

[1] https://llvm.org/docs/Contributing.html#format-patches

Thanks in advance.

**Comment by aaupov** [comment]
No, there are no BOLT-specific clang-format scripts. Some existing code may not adhere to the current formatting rules (may have been added before formatting rules were introduced/changed). 
The best practice is to keep formatting as is for existing code and only apply clang-format to your changes using the following command:
`git diff -U0 --no-color --relative HEAD^ | clang-format-diff.py -p1 -i`
