### ISSUE TITLE
[Question] git pull failed for rebased branch

### ISSUE THREAD

**Issue by fengali** [facebookincubator/BOLT#180]
when I try to update rebased branch,  I will get merge failed.
Like:
Automatic merge failed; fix conflicts and then commit the result.

But, I doesnot modify any code of bolt.

PS: my git version:
git version 2.24.3 (Apple Git-128)

Thank you.

**Comment by yota9** [comment]
Hello @fengali . 
The rebased branch is usually force updated, so git could not rebase it properly. You can get the latest updates with:
```
git fetch
git reset --hard origin/rebased
```
In case you don't have any changes.

**Comment by fengali** [comment]
it works. thank @yota9 for replying.
