### ISSUE TITLE
inline-debug-info test is failing

### ISSUE THREAD

**Issue by yota9** [facebookincubator/BOLT#181]
Hello! 
The inline-debug-info is currently failing on linux, seems to be call address is screwed after inlining.
Thank you!

**Comment by aaupov** [comment]
We're aware of the issue. Ubuntu uses Intel CET-enabled PLT section (.plt.sec) which messes up the disassembly of `call puts`. @maksfb was looking at it.

**Comment by aaupov** [comment]
Should be resolved now. The test passes with 403b668
