### ISSUE TITLE
[Question] Status of LLVM integration?

### ISSUE THREAD

**Issue by h-vetinari** [facebookincubator/BOLT#183]
Hey all

I looked through the issues here (and I see the [`rebased`](https://github.com/facebookincubator/BOLT/commits/rebased) branch), but I cannot tell what the current status of LLVM integration is, and thought it might be helpful (perhaps also for others) to have an issue to track it.

Last public update I'm aware of is [this](https://lists.llvm.org/pipermail/llvm-dev/2021-April/149799.html).
Edit July 2021: another [update](https://lists.llvm.org/pipermail/llvm-dev/2021-July/151755.html)

Thanks!

**Comment by aaupov** [comment]
We're in process of resolving the technical issues that need to be addressed before we can start talking with the community about the actual integration. Specifically, there are two areas: our changes to LLVM libraries, and testing infrastructure.
Regarding the changes: we're upstreaming our changes made to LLVM libraries or refactoring BOLT codebase to avoid them. 
We had 23 such changes, of which 15 are resolved and 8 are WIP or TBD:
1. Alignment for Macro-op Fusion (https://reviews.llvm.org/D97982): WIP, review is pending for 4 months now
2. TrapFillValue (https://reviews.llvm.org/D102287): TBD, plan is to reimplement in BOLT, easy
3. TAILJMP encoding (https://reviews.llvm.org/D102297?vs=on&id=344627#toc): TBD, reimplement in BOLT, medium
4. Support DWARF expressions in CFI instructions (https://reviews.llvm.org/D98301): TBD, reimplement in BOLT, hard
5. Extend DWARFAbbreviationDeclaration::AttributeSpec with AttrOffset and FormOffset (https://reviews.llvm.org/D102291): TBD, perhaps reimplement, medium
6. [DWARF] AbsoluteAddr: TBD, hard
7. [DWARF] Add UsesRelocs DWARFContext property: TBD, hard
8. [DWARF] Introduce RefHandler to parse external refs in frame data: TBD, hard

**Comment by h-vetinari** [comment]
Thanks for the detailed response, much appreciated!

**Comment by rafaelauler** [comment]
Thanks for starting this thread.

About number 4, I'm on it and it is going to be a very weird gymnastics to do that in BOLT (if possible at all) without adding our changes to LLVM to support emitting DWARF expressions. So I'll probably push D98301 forward.

**Comment by aaupov** [comment]
For those tracking the status, here's the remaining set of patches:
1. [DWARF] Support DWARF expressions in CFI instructions: https://reviews.llvm.org/D107515 (WIP)
2. [DWARF] Find offset of attribute: https://reviews.llvm.org/D107874 (WIP)
3. [DWARF] Add findAttribute to DWARFAbbreviationDeclaration: https://reviews.llvm.org/D107875 (WIP)
4. [DWARF] AbsoluteAddr: https://reviews.llvm.org/D105747 (TBD)
5. [DWARF] Introduce RefHandler to parse external refs in frame data: https://reviews.llvm.org/D105746 (TBD)

Alignment for Macro-op Fusion has been disabled in the open-source version.

**Comment by h-vetinari** [comment]
As of right now, I see LLVM main has ~400'800 commits and BOLT main has ~401'550 (after what looks like a rebase). Is upstreaming those 750 commits panned for the initial working LLVM implementation, or roughly how much of that is still necessary?

Without pressure (but curiosity), do you consider integration a realistic goal for LLVM 14 (branching probably end of Jan' 22)?

**Comment by maksfb** [comment]
After the most recent rebase, the majority of the extra commits should be local to `/bolt` directory. For us it makes sense to upstream those changes as a single component without individual commit review, similar to how flang front end was added. 

Inclusion in LLVM 14 is the goal.

**Comment by h-vetinari** [comment]
> For us it makes sense to upstream those changes as a single component without individual commit review, similar to how flang front end was added.

I would double- & triple-check the details of this approach with upstream, to see that there's no misunderstanding, resp. what conditions need to be satisfied for such a code drop. I mention this because there were some pretty large and long-winded gymnastics involved to land the initial flang contribution while maintaining a curated history.

> Inclusion in LLVM 14 is the goal.

That's great news!

**Comment by rafaelauler** [comment]
Starting in our last rebase from Oct 1st (made public today), 100% of our commits should be local to /bolt and do not interfere with the rest of LLVM. Everything that concerns other LLVM components has been reviewed by the community and has landed in the llvm monorepo, and we work to address any changes that concerns the bolt/ folder itself in this github (using github's issue tracker), since it is not realistic to open 900 phabricator reviews for all diffs that touch the bolt/ folder, which comprises about 5 years of project history. Outside of the bolt/ folder, we only have a single change to llvm that is to the cmake file, to advertise to the build system that we have a new project called bolt.

If I remember correctly, flang did a merge commit to insert their project history, and that looked to me like the best approach to merge a project into the monorepo. In that way, it is easy for the llvm community to ignore all of BOLT's historic commits by just skipping through the merge commit (when doing a bisect, for example).  If you try to fetch a commit from BOLT's history, it is probably not going to build, since we are doing constant rebases of a large project, so the commits are there for history only (and blame). I think this is pretty similar to what flang did.  If we wanted to have old commits that are buildable, we would need to be constantly doing merge commits (instead of rebases), which would significantly complicate the commit graph.

**Comment by h-vetinari** [comment]
> If I remember correctly, flang did a merge commit to insert their project history,

It's prehaps a good idea to have a look through the mailing list how much work went into that merge (e.g. [1](https://lists.llvm.org/pipermail/llvm-dev/2020-February/139378.html) ff., [2](https://lists.llvm.org/pipermail/llvm-dev/2020-March/139943.html) ff., [3](https://lists.llvm.org/pipermail/llvm-dev/2020-March/140180.html)).

That's what I meant above with "double- & triple-check the details of this approach with upstream" - it's good to have visibility & alignment & buy-in on an explicit plan. Even with a merge, things will surely come up. Double-checking that earlier rather than later would then go some way towards avoiding a scenario where BOLT misses the next release, for example.

**Comment by h-vetinari** [comment]
Great to see the mailing list [post](https://lists.llvm.org/pipermail/llvm-dev/2021-November/153551.html) about the integration plan! I guess this can be closed in favour of #248?

**Comment by maksfb** [comment]
@h-vetinari, thank you for raising the concerns about the integration!

**Comment by yota9** [comment]
Hello facebook team! I would like to congratulate you with the integration of BOLT project in to LLVM! This is extremely cool! Thank you for your for your hard work! :))

**Comment by aaupov** [comment]
> Hello facebook team! I would like to congratulate you with the integration of BOLT project in to LLVM! This is extremely cool! Thank you for your for your hard work! :))

Hi Vladislav! Thank you for your contributions and congratulations on your work becoming a part of LLVM!

**Comment by andreybokhanko** [comment]
Congratulations to the Facebook (err... I meant Meta :)) team for this amazing acheivement!

Hopefully, this will enable further adoption and development of BOLT!

Yours,
Andrey
