### ISSUE TITLE
llvm.patch missing in main branch

### ISSUE THREAD

**Issue by chen-hu-97** [facebookincubator/BOLT#193]
Now the default branch is main which doesn't include llvm.patch. It fails to build if we follow the steps in  https://github.com/facebookincubator/BOLT/tree/main/bolt#manual-build :

> ...
> git clone https://github.com/facebookincubator/BOLT llvm-bolt
> cd ..
> patch -p 1 < tools/llvm-bolt/llvm.patch
> ...

Is following solution right?
$ git clone https://github.com/facebookincubator/BOLT llvm-bolt **--branch master**
But master branch is stale?

**Comment by yota9** [comment]
Hello! On the current branch (main) the bolt is integrated to llvm, you don't have to patch it. Use cmake with DLLVM_ENABLE_PROJECTS="bolt" option to build Bolt.

**Comment by aaupov** [comment]
@chen-hu-97:
Thanks for flagging the issue. Our documentation got out of sync as we moved to rebased branch (now called main).
In the meantime, you can follow our Docker build instructions: https://github.com/facebookincubator/BOLT/blob/main/.github/workflows/Dockerfile

**Comment by aaupov** [comment]
The documentation is updated: see [Manual Build](https://github.com/facebookincubator/BOLT#manual-build)
