### ISSUE TITLE
build latest bolt fail

### ISSUE THREAD

**Issue by zpget** [facebookincubator/BOLT#194]
gcc: gcc8.2
system: kernel 3.10.0.514.26.2.el7.x86_64

build error:
lvm-bolt/llvm/lib/Support/BinaryStreamError.cpp:9:
llvm-bolt/llvm/lib/Support/BinaryStreamError.cpp
gcc-8.2/include/c++/8.2.0/cstdlib:137:11: error: ‘::at_quick_exit’ has not been declared

what depends need?

**Comment by rafaelauler** [comment]
This is LLVM code. I would start by checking that your setup is able to build LLVM master (http://llvm.org and https://github.com/llvm/llvm-project/) before building BOLT.

**Comment by aaupov** [comment]
Let us know if you run into BOLT build issues, provided that LLVM builds successfully.
