### ISSUE TITLE
Classify Vector instructions using BOLT and MC layer.

### ISSUE THREAD

**Issue by Sameeranjoshi** [facebookincubator/BOLT#195]
I am trying to classify `MCInst` represented vector instructions specific to X86 using BOLT.
Specifically I am interested to check for the packed (double/single) instructions (PD/PS) based instructions at `MCInst` level.

I see 2 approaches :
1. Implement some high level routine( `isVector`) in `X86MCPlusBuilder.cpp` similar to the ones already present in the file(e.g `isCMP`) 
 The drawback I see with this approach(I may be wrong, correct me if that's the case) is, we should be aware of all the opcode related to vector instructions, also this list could be too big, as well as it may change with changes in newer processors releases.

2. Use the various flags from the instruction format and try to check in a more generic way.
    `MCInstDesc` contains `TSFlags` 
something like 
```    
  bool isVecInst(const MCInst &Inst) const override {
    auto const &Desc = Info->get(Inst.getOpcode());
    return (Desc.TSFlags & X86II::OpPrefixMask) == X86II::PD;
  }
```
 or 
 ```
   bool isVecInst(const MCInst &Inst) const override {
    auto const &Desc = Info->get(Inst.getOpcode());
 	return Desc.TSFlags & X86II::PD;
  }
 ```
 Although this approch didn't work as expected and gives wrong results.

 I have 2 questions based on above:
 1. Which approach do you folks suggest ? 
 	If first one, is there a way we use the tablegen infrastructure which might have list of all the possible vector instructions ?

 2. If second one, is there some way to know more about how does the encoding in MC layer look like and how can we classify various instructions specifically vector as of now? ( I did try to search the internet and tried to read the `MCInstrDesc` and `MCInst` classes, I could understand the representation of these classes but didn't understand enough on classifying various instructions and even more details of these classes)

 Also if someone can point some good tutorial/way to understand the MC layer that would be very much appreciated.

 Thanks in advance.

**Comment by aaupov** [comment]
Hi Sameeran!
I think the second approach is a better one. We use custom matching (eg `isCMP`) in cases where that information isn't available in the tablegen definition. For your use case, it makes more sense to rely on tablegen-provided information.

Regarding the check for PS/PD instructions: are you trying to capture the encoding or the execution domain aspect? If the former, the approach with checking the OpPrefixMask is right (and'ing with PD or PS). If the latter, there's an `X86InstrInfo::getExecutionDomain` interface that can report if an instruction belongs to a SSEPackedSingle or SSEPackedDouble domain (as defined in `X86InstrFormats.td`). You would need to expose this interface through MCPlusBuilder though.

**Comment by Sameeranjoshi** [comment]
Hello Amir,
Thanks for quick replies.

I am using the first approach of capturing encoding aspect, I am unaware of the second approach, although I tried to see the interface of `getExecutionDomain(const MachineInstr &)` which seems to be accepting `MachineInst` and not `MCInst`.

Given the first approach we have one small confusion regarding the `SHLX32rr` instruction, as it was classified as a vector instruction by the first approach.

Below is the output snippet from the `X86.td` file when expanded with `llvm-tblgen`.
There are 2 thoughts from our end.
Looking at the instruction opcode I would say that it's **not a vector instruction.**
Checking the prefixes like `VEX/T8PD` I would assume it's **a vector instruction.**
`
def SHLX32rr {​​​​​​​  // InstructionEncoding Instruction X86Inst I **VEX** Sched T8 **T8PD**
`

So is it a true vector operation - which really does vector computation using vector register sets ? 
If it's not a vector instruction, does it mean `llvm-tblgen` is generating wrong output ?

Thanks again

**Comment by aaupov** [comment]
> I am using the first approach of capturing encoding aspect, I am unaware of the second approach, although I tried to see the interface of `getExecutionDomain(const MachineInstr &)` which seems to be accepting `MachineInst` and not `MCInst`.

You're right. This interface unfortunately is not applicable (MachineInst is lowered into MCInst). Sorry for confusion. 

> 
> Given the first approach we have one small confusion regarding the `SHLX32rr` instruction, as it was classified as a vector instruction by the first approach.
> 
> Below is the output snippet from the `X86.td` file when expanded with `llvm-tblgen`.
> There are 2 thoughts from our end.
> Looking at the instruction opcode I would say that it's **not a vector instruction.**
> Checking the prefixes like `VEX/T8PD` I would assume it's **a vector instruction.**
> `def SHLX32rr {​​​​​​​ // InstructionEncoding Instruction X86Inst I **VEX** Sched T8 **T8PD**`
> 
> So is it a true vector operation - which really does vector computation using vector register sets ?
> If it's not a vector instruction, does it mean `llvm-tblgen` is generating wrong output ?
> 
> Thanks again

SHLX is an exception, as it's an integer instruction encoded using VEX prefix. All such exceptions are listed in Intel's SDM Volume 2, 2.5.1 Exceptions Type 13 (VEX-Encoded GPR Instructions):
>ANDN, BEXTR, BLSI, BLSMSK, BLSR, BZHI, MULX, PDEP, PEXT, RORX, SARX, SHLX, SHRX
