### ISSUE TITLE
PMU Hardware doesn't support sampling/overflow-interrupts

### ISSUE THREAD

**Issue by shuzhang1989** [facebookincubator/BOLT#2]
I got this error on our host when doing the perf profiling when "-j" is enabled. looks its needed to do branch optimization

if i remove "-j", the perf data fed into BOLT will lead to the following error from BOLT:
`llvm-bolt: ../tools/llvm-bolt/src/BinaryFunction.cpp:1726: bool llvm::bolt::BinaryFunction::buildCFG(): Assertion `ToBB && "cannot find BB containing TO branch"' failed.`

any workaround?

**Comment by maksfb** [comment]
Could it be that your input to BOLT is compiled with `-fpic/-fPIC`? The workaround would be to recompile without it, or to add `-fno-jump-tables` option while we are working on adding a support for special cases of PIC jump tables. Are you running `perf` on a VM?

**Comment by shuzhang1989** [comment]
@maksfb looks my binary doesn't compile with -fPic. 
I am running perf on aws hosts

**Comment by shuzhang1989** [comment]
Tried to compile with <-fno-jump-tables> but no luck.

**Comment by maksfb** [comment]
@shuzhang1989: could you try with the latest version? You don't need `-fno-jump-tables` anymore.

**Comment by shuzhang1989** [comment]
@maksfb error gone! thanks for the quick fix!
