### ISSUE TITLE
[bug]Dwarf Error: Cannot handle DW_FORM_indirect in updating debug_abbrev

### ISSUE THREAD

**Issue by Haishan312** [facebookincubator/BOLT#236]
Hi, 

   when using `--update-debug-sections` options, llvm-bolt prints a lot of BOLT-ERROR/BOLT-WARNING,
such as:
`BOLT-WARNING: empty location list detected at 0xf595166 for DIE at 0x18e9511e in CU at 0x18e849dc
`
`BOLT-ERROR: cannot update ranges for DIE at offset 0x18e96584` 

BOLT-WARNING:
```
.debug_info contents:
0x18e950fa:   DW_TAG_subprogram
                DW_AT_abstract_origin   (0x18e950e0 "_ZNSt3tr116_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE10_M_destroyEv")
                DW_AT_linkage_name      ("_ZNSt3tr116_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE10_M_destroyEv")
                DW_AT_low_pc    (0x0000000000000000)
                DW_AT_high_pc   (0x0000000000000012)
                DW_AT_frame_base        (DW_OP_call_frame_cfa)
                DW_AT_object_pointer    (0x18e9511e)
                DW_AT_GNU_all_call_sites        (true)
                DW_AT_sibling   (0x18e9513c)
0x18e9511e:     DW_TAG_formal_parameter
                  DW_AT_abstract_origin (0x18e950ef "this")
                  DW_AT_location        (0x0f595156: )
```

BOLT-ERROR due to dwarf information
`0x18e96584:     DW_TAG_lexical_block`
without DW_AT_low_pc and DW_AT_high_pc.

My binary is compiled with Gcc-4.9.2 and '-g' compile option.

Finally, when I debug the new binary with gdb-7.6, This new binary loses line information and function information, even global variable information.
I am a newbie about dwarf. More help would be appreciated.

**Comment by maksfb** [comment]
Are you using split DWARF for the binary? Can you repro using a smaller binary that you can share?

**Comment by ayermolo** [comment]
@Haishan312 can you try with latest from llvm upstream?

**Comment by Haishan312** [comment]
> 

Latest code works ok

**Comment by ayermolo** [comment]
ok, closing
