### ISSUE TITLE
[Question] How can l remove useless segments?

### ISSUE THREAD

**Issue by getianao** [facebookincubator/BOLT#242]
Hi,
According to #93 , `.bolt.org.text` can be useless If the binary links with `--emit-relocs` and not specify `-lite`.

But I try to remove`.bolt.org.text` segment of my program which only contains a simple loop using  `objcopy`, and the stripped program can't work. It prints `Inconsistency detected by ld.so: rtld.c: 1494: dl_main: Assertion 'GL(dl_rtld_map).l_libname' failed!`  How can I fix it?

And can you give me more advise to reduce the generated binary's code-size？Thanks :)

More details about the program:
```
%.o: %.C
	$(CXX) $(OPT)  -c $< -o $@ $(CFLAGS)

$(BIN):$(LINKEDBIN)
	$(CXX) $(OPT)     $< -o $@ $(CFLAGS) -Wl,--emit-relocs

bolt: $(BIN)
	${BOLT} $(BIN) -instrument -o $(BIN).ins
	./$(BIN).ins

test:
	${BOLT} $(BIN) -o $(BIN).bolt -data=$(FDATA_PATH)/prof.fdata -reorder-blocks=cache+ -reorder-functions=hfsort -split-functions=2 -split-all-cold -split-eh -dyno-stats --no-huge-pages  -v=1

strip:
	objcopy --remove-section .bolt.org.text  $(BIN).bolt $(BIN).bolt.strip
```

**Comment by maksfb** [comment]
> @maksfb BTW is there any reasons to support binaries without relocations? It needs extra code, extra tests & etc, but I'm not sure if there are any reason to support this, since the optimization effects are limited. What do you think about it?

For optimizing in-house applications, it does make sense to support the relocation mode only. However, there are other applications, beyond optimizations that make the non-relocation mode useful. E.g. being able to look at CFGs of functions in arbitrary binaries. I imagine there will be more applications for this mode as BOLT framework for binary analysis grows.

**Comment by getianao** [comment]
@maksfb Hi,  about the issue with `objcopy` mentioned at the beginning, I tried to enable `use-gnu-stack` option and then the stripped program works well. 

So creating PHDR table in a segment may be the reason why `objcopy` can't work with the generated binary, is it right? And what are the downsides if I enable `use-gnu-stack` option.

**Comment by getianao** [comment]
@maksfb And another question is about identical code folding: If I enable `-use-old-text` option and successfully place the new code in the original `.text`, although some identical fucntions have been folded, the size of original `.text` segment doesn' change, so it doesn't affect binary size much and there may be a small size reduction due to the reduction of symbols and strings. If my understanding is correct, is there any way that can change section's size so that useless empty space in section can be avoid? I'm curious about ti and really appreciate for your patient answer :)

**Comment by maksfb** [comment]
> @maksfb Hi, about the issue with `objcopy` mentioned at the beginning, I tried to enable `use-gnu-stack` option and then the stripped program works well.
> 
> So creating PHDR table in a segment may be the reason why `objcopy` can't work with the generated binary, is it right? And what are the downsides if I enable `use-gnu-stack` option.

Yes, binutils `objcopy` cannot deal with a program header table in the new segment. `-use-gnu-stack` option reuses another entry (GNU_STACK) in the table for the new segment.
