### ISSUE TITLE
Preparation for LLVM monorepo

### ISSUE THREAD

**Issue by maksfb** [facebookincubator/BOLT#248]
List of issues to close before the integration:
- [x] Convert GH issue format in commit messages.
- [x] Remove references to internal tasks.
- [x] Add CODE_OWNERS.txt
- [x] Resolve Windows build issues to make BOLT working on the platform.
- [x] Move and update README.md for BOLT.

**Comment by aaupov** [comment]
Feedback from [Phoebe Wang](https://lists.llvm.org/pipermail/llvm-dev/2021-December/154420.html):
- [ ] Use the monorepo of LLVM in the example (Optimizing Clang)
- [ ] "not implemented"
- [ ] inconsistent braces
- [ ] Some files don’t have a descriptions in the first line
- [ ] format should be consistent for file descriptions
