### ISSUE TITLE
Is .Deb files supported

### ISSUE THREAD

**Issue by Sambhrama754** [facebookincubator/BOLT#249]
??
Tq

**Comment by Sambhrama754** [comment]
@drodriguez help 
Can we out put binaries as .Deb files

**Comment by aaupov** [comment]
What exactly do you mean by deb binaries? Generally BOLT would support binaries compiled on Debian using the workflow outlined in the wiki. Speaking of binaries shipped in .deb packages, I expect a number of issues optimizing them:
1. They're compiled with GCC with function splitting by default (-freorder-blocks-and-partition), which is discouraged.
2. They are stripped of symbol table preventing the proper identification of cold function fragments.
3. They're linked without relocations preserved in the binary, which restricts function reference identification.

**Comment by Sambhrama754** [comment]
@aaupov oh I think we can patch it
