### ISSUE TITLE
Change -fuse-ld=ld.lld to -fuse-ld=lld

### ISSUE THREAD

**Issue by MaskRay** [facebookincubator/BOLT#270]
`-fuse-ld=lld` (`-fuse-ld=word`) is a more supported way to specify ld.lld. Clang reserves the right to do linker option dispatch on `-fuse-ld=lld` in the future.

(Note: `-fuse-ld=relative/path` and `-fuse-ld=/absolute/path` are deprecated. If you want to use ld.lld but with a different path, specify  `-fuse-ld=lld --ld-path=/absolute/path`: bazelbuild/bazel#13252 )

(Note: don't test exact addresses when `-fuse-ld=lld` is used. ld reserves the right to change layout.)

**Comment by rafaelauler** [comment]
I agree testing against exact addresses is a bad idea and I'll change tests that rely on that. 

I changed our -fuse-ld=ld.lld invocations but I'm getting: 
lld is a generic driver.
Invoke ld.lld (Unix), ld64.lld (macOS), lld-link (Windows), wasm-ld (WebAssembly) instead
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by rafaelauler** [comment]
Oh, LIT is replacing my lld string with a full path.

**Comment by aaupov** [comment]
Done: 7a1af48d2f032dbd4a7dbd939954c61b28aa0837
