### ISSUE TITLE
Binary optimization for dynamically loaded library from executable?

### ISSUE THREAD

**Issue by wonjeon** [facebookincubator/BOLT#279]
Hello. I have a question for you. 
Does BOLT work for an executable with dynamically loading library?
Is any special profiling technique needed for perf and BOLT?
Thanks in advance.

**Comment by maksfb** [comment]
You have to separately optimize the executable and its dependencies, i.e. one at a time. The profile can be shared though. E.g.:
```
$ perf record -e cycles -j any,u -- ./a.out
$ llvm-bolt -p perf.data a.out -o a.out.bolt <bolt-options>
$ llvm-bolt -p perf.data liba.so -o liba.bolt.so <bolt-options>
$ mv liba.so liba.old.so && mv lib.bolt.so lib.so

**Comment by wonjeon** [comment]
Thanks. Will close this issue.
