### ISSUE TITLE
Error reading bolt data input file: line 1, column 43: expected single char for mispred bit

### ISSUE THREAD

**Issue by J-cztery** [facebookincubator/BOLT#28]
Intel compiler + gcc 4.8.5. 
Now that https://github.com/facebookincubator/BOLT/issues/23 has been fixed, i see this: 
```
PERF2BOLT: Starting data aggregation job for perf.data
PERF2BOLT: Spawning perf-script job to read branch events
PERF2BOLT: Spawning perf-script job to read mem events
PERF2BOLT: Spawning perf-script job to read tasks
BOLT-INFO: Target architecture: x86_64
BOLT-INFO: binary build-id is:     270c5a1e626f1b4f158599ab044340721e063450
PERF2BOLT: matched build-id and file name
BOLT-INFO: first alloc address is 0x400000
BOLT-INFO: creating new program header table at address 0x800000, offset 0x400000
BOLT-INFO: enabling relocation mode
BOLT-WARNING: sizes differ for function __intel_memcpy. FDE : 6055; symbol table : 6064. Using max size.
BOLT-WARNING: sizes differ for function __intel_new_memcpy. FDE : 6055; symbol table : 6064. Using max size.
BOLT-INFO: forcing -jump-tables=move as PIC jump table was detected in function _ZL28read_encoded_value_with_basehmPKhPm/eh_personality.o/1(*2)
BOLT-WARNING: unable to disassemble instruction at offset 0x6c8 (address 0x51d0b8) in function __intel_avx_rep_memcpy
BOLT-WARNING: unable to disassemble instruction at offset 0x165 (address 0x51e315) in function __intel_new_memcpy(*2)
PERF2BOLT: Waiting for perf tasks collection to finish...
PERF2BOLT: Parsing perf-script tasks output
PERF2BOLT: Input binary is associated with 1 PID(s)
PERF2BOLT: Waiting for perf events collection to finish...
PERF2BOLT: Aggregating branch events...
Error reading bolt data input file: line 1, column 43: expected single char for mispred bit
Found: 0x7f2c9cf100fe
PERF2BOLT: Failed to parse samples
PERF2BOLT: Wrote 0 objects and 0 memory objects to perf.fdata
```
Is my perf.data broken?

**Comment by maksfb** [comment]
It could be the new format of `perf` output. What is the `perf` version that your are running and on what hardware? Ideally I'd like to see the output of `perf script -F pid,brstack ...`, or at least at a part of it that was causing the trouble.

Also, our diagnostics was broken. Could you please pull the latest changes and re-run the command?

**Comment by J-cztery** [comment]
./perf --version
perf version 3.10.0-693.5.2.el7.x86_64.debug
The hardware is Intel Xeon Phi 7250. The hardware i am running perf2bolt, though is Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz, same kernel and OS version, Centos 7. 

Will respond your other questions later. 
Thanks.

**Comment by J-cztery** [comment]
With the fixed diagnostics it looks like this: 
```
Error reading bolt data input file: line 1, column 43: expected single char for mispred bit
Found: -
PERF2BOLT: Failed to parse samples
```

**Comment by J-cztery** [comment]
`sudo perf script -f -F pid,brstack`
First few lines of output: 
```
 7466  0xffffffff816ac32c/0x7f2c9cf100fe/-/-/-/0 
 7466  0xffffffff816ac32c/0x7f2c9cf100fe/-/-/-/0  0xffffffff816ac32c/0x7f2c9cf100fe/-/-/-/0 
 7466  0xffffffff816ac32c/0x7f2c9cf100fe/-/-/-/0  0xffffffff816ac32c/0x7f2c9cf100fe/-/-/-/0  0xffffffff816ac32c/0x7f2c9cf100fe/-/-/-/0 
 7466  0xffffffff816ac32c/0x7f2c9cf100fe/-/-/-/0  0xffffffff816ac32c/0x7f2c9cf100fe/-/-/-/0  0xffffffff816ac32c/0x7f2c9cf100fe/-/-/-/0  0xffffffff816ac32c/0x7f2c9cf100fe/-/-/-/0
```

**Comment by maksfb** [comment]
For the `perf` issue it's an easy fix, assuming that otherwise the output format is the same. If you can upgrade to `perf` version `4.5` or later it might be easier to guarantee that. The more serious issue I see is with `__intel_avx_rep_memcpy` and `__intel_new_memcpy` functions referenced in the log. We'll need to add a support for jump tables / data in code, otherwise we cannot process them in relocation mode. The workaround is to use `-relocs=0`, and it is not good for performance.

**Comment by J-cztery** [comment]
Grabbed perf from kernel 4.5: 
`$ perf --version`
`perf version 4.5.gb562e4`

Collected traces : 
`./perf record -e cycles:u -j any,u -o perf.data -- (...)`

Then on a different machine after copying the perf.data: 
`sudo perf script -F pid,brstack -f`
```
172359  0xffffffff816ac32c/0x7fc9b763c0fe/-/-/-/0 
172359  0xffffffff816ac32c/0x7fc9b763c0fe/-/-/-/0  0xffffffff816ac32c/0x7fc9b763c0fe/-/-/-/0 
172359  0xffffffff816ac32c/0x7fc9b763c0fe/-/-/-/0  0xffffffff816ac32c/0x7fc9b763c0fe/-/-/-/0  0xffffffff816ac32c/0x7fc9b763c0fe/-/-/-/0 
```

**Comment by J-cztery** [comment]
I guess the problem here is not in perf version but possibly perf on KNL not supporting the correct hw event. 
From: 
https://gitlab.imag.fr/kaunetem/linux-kaunetem/commit/dc323ce8e72d6d1beb9af9bbd29c4d55ce3d7fb0
`M/P/-: M=branch target mispredicted or branch direction was mispredicted, P=target predicted or direction predicted, -=not supported`

I will have a look how perf gets it.

**Comment by J-cztery** [comment]
Yep this one is a KNL issue. On other CPU i got: 
`0xffffffff816ac32c/0x7f7b322365a0/P/-/-/0`

**Comment by maksfb** [comment]
Interesting. We only use misprediction bit for ICP optimization, so it should be safe to ignore it. I'll add a patch. Thank you for the investigation.

**Comment by J-cztery** [comment]
Great, thanks! So how about the intel memcpy (and others) replacements? 
Is there anything i can do to help? Should a new issue be raised?

**Comment by maksfb** [comment]
Is there any way to force intel compiler to use libc functions? It justifies the new issue in any case.

**Comment by J-cztery** [comment]
Looks good, closing: 

PERF2BOLT: Waiting for perf tasks collection to finish...
PERF2BOLT: Parsing perf-script tasks output
PERF2BOLT: Input binary is associated with 1 PID(s)
PERF2BOLT: Waiting for perf events collection to finish...
PERF2BOLT: Aggregating branch events...
**PERF2BOLT-WARNING: misprediction bit is missing in profile**
