### ISSUE TITLE
How will bolt integrate with llvm in the future?

### ISSUE THREAD

**Issue by dangit815** [facebookincubator/BOLT#287]
At present, bolt source code has been integrated into llvm. Will bolt processing flow be further combined with llvm in the future? For example, bolt uses **llvm IR** and **llvm optimization pass** to improve the effect of post-link optimizing?

Because in the binary phase, bolt can see more optimization opportunities, but currently bolt only supports BB block rearrangement, function rearrangement and other optimization, and its ability is weak. If the optimization ability of llvm can be used, it is expected to obtain greater optimization effect.

**Comment by dangit815** [comment]
cc @rafaelauler @maksfb @aaupov

**Comment by rafaelauler** [comment]
I think I answered that in https://discourse.llvm.org/t/want-to-know-about-bolt-and-llvm-post-planning/61674 but let me know if there are any remaining questions.

**Comment by dangit815** [comment]
Thank you. In addition, where can I see the follow-up plan of bolt?

**Comment by maksfb** [comment]
I've added a list of BOLT Open Projects at: https://discourse.llvm.org/t/bolt-open-projects/61857

**Comment by dangit815** [comment]
I see that "Raising IR" is mentioned here. What is the attitude of bolt community towards this direction? @maksfb @rafaelauler seem to have conflicting views on this direction.
![image](https://user-images.githubusercontent.com/27342851/164361682-f7085c16-98bf-42e0-9dc0-8c5c55bb8224.png)

**Comment by rafaelauler** [comment]
I'm not opposed to the idea, but it is a non-trivial project.
