### ISSUE TITLE
Error reading BOLT data input file: line 13, column 0: malformed field

### ISSUE THREAD

**Issue by skpgkp1** [facebookincubator/BOLT#29]
Bolt error on gcc 5.5.0 compiled hhvm.

$ perf --version
perf version 4.17.2

$ ../bolt/build/bin/perf2bolt --version
LLVM (http://llvm.org/):
  LLVM version 7.0.0svn
  DEBUG build with assertions.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: skylake-avx512

$ ../bolt/build/bin/perf2bolt -p perf.data.gcc -o perf.fdata `which hhvm`
PERF2BOLT: Starting data aggregation job for perf.data.gcc
PERF2BOLT: Spawning perf-script job to read branch events
PERF2BOLT: Spawning perf-script job to read mem events
PERF2BOLT: Spawning perf-script job to read tasks
BOLT-INFO: Target architecture: x86_64
BOLT-WARNING: build-id will not be checked because we could not read one from input binary
BOLT-INFO: first alloc address is 0x400000
BOLT-INFO: creating new program header table at address 0x5000000, offset 0x4c00000
BOLT-INFO: enabling relocation mode
BOLT-WARNING: non-standard function reference (e.g. bitmask) detected against function _ZN5folly18BucketedTimeSeriesIlNS_16LegacyStatsClockINSt6chrono8durationIlSt5ratioILl1ELl1EEEEEEE13updateBucketsENS2_10time_pointIS7_S6_EE(*2) from function _ZN4HPHPL12start_serverERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi.constprop.756/program-functions.cpp/1(*2)
BOLT-WARNING: non-standard function reference (e.g. bitmask) detected against function _ZN4HPHP3jit3x6419assert_tc_saved_ripEPv from function _ZN4HPHP3jit3x6414emitCallToExitERNS_9DataBlockES3_RKNS0_11UniqueStubsE
BOLT-WARNING: non-standard function reference (e.g. bitmask) detected against function _ZN4HPHP3jit3x6419assert_tc_saved_ripEPv from function _ZN4HPHP3jit3x6414emitCallToExitERNS_9DataBlockES3_RKNS0_11UniqueStubsE
BOLT-WARNING: non-standard function reference (e.g. bitmask) detected against function _ZN4HPHP3jit11MethodCache20handlePrimeCacheInitILb0EEEvjPNS_6ActRecEPNS_10StringDataEPNS_5ClassES8_m from function _ZN4HPHP3jit11UniqueStubs7emitAllERNS0_9CodeCacheERNS_5Debug9DebugInfoE
BOLT-WARNING: non-standard function reference (e.g. bitmask) detected against function _ZN4HPHP3jit11MethodCache20handlePrimeCacheInitILb1EEEvjPNS_6ActRecEPNS_10StringDataEPNS_5ClassES8_m from function _ZN4HPHP3jit11UniqueStubs7emitAllERNS0_9CodeCacheERNS_5Debug9DebugInfoE
BOLT-WARNING: non-standard function reference (e.g. bitmask) detected against function _ZN4HPHP3jit11MethodCache14handleSlowPathILb0EEEvjPNS_6ActRecEPNS_10StringDataEPNS_5ClassES8_m from function _ZN4HPHP3jit11UniqueStubs7emitAllERNS0_9CodeCacheERNS_5Debug9DebugInfoE
BOLT-WARNING: non-standard function reference (e.g. bitmask) detected against function _ZN4HPHP3jit11MethodCache14handleSlowPathILb1EEEvjPNS_6ActRecEPNS_10StringDataEPNS_5ClassES8_m from function _ZN4HPHP3jit11UniqueStubs7emitAllERNS0_9CodeCacheERNS_5Debug9DebugInfoE
BOLT-WARNING: 1 collisions detected while hashing binary objects. Use -v=1 to see the list.
PERF2BOLT: Waiting for perf tasks collection to finish...
PERF2BOLT: Parsing perf-script tasks output
Error reading BOLT data input file: line 13, column 0: malformed field
PERF2BOLT: Failed to parse tasks
PERF2BOLT: Waiting for perf events collection to finish...
PERF2BOLT: Aggregating branch events...
PERF2BOLT: Read 37 samples and 807 LBR entries
PERF2BOLT: Traces mismatching disassembled function contents: 35 (4.5%)
PERF2BOLT: Out of range traces involving unknown regions: 549 (71.3%)
PERF2BOLT: Wrote 132 objects and 0 memory objects to perf.fdata

**Comment by rafaelauler** [comment]
Hi, thanks for reporting! Can you run the following command with your perf.data using your perf and paste the first 20 lines of the result here?

perf script --show-task-events -i perf.data.gcc

**Comment by skpgkp1** [comment]
Thanks Maksim for helping me out on this. With right perf options this issue got fixed. Corrected perf options are
 
"-a -e cycles:u -j any,u".

**Comment by maksfb** [comment]
For the record, we don't support data collected with `-g` option at the moment.

**Comment by Haishan312** [comment]
@rafaelauler I  got the same error with perf-5.10. and using record command is `perf record -e cycles:u -j any,u -a -- /usr/bin/ls -l`.
I find the parseString which cannot handle the format `"c1d2c0bead01849e", ' ' <repeats 25 times>, "/usr/bin/ls\n"`
```
perf script --show-task-events
      swapper     0 [000]     0.000000: PERF_RECORD_FORK(1:1):(0:0)
         systemd     0 [000]     0.000000: PERF_RECORD_COMM: systemd:1/1
         swapper     0 [000]     0.000000: PERF_RECORD_FORK(100979:100979):(0:0)
            bash     0 [000]     0.000000: PERF_RECORD_COMM: bash:100979/100979
         systemd     0 [000]     0.000000: PERF_RECORD_FORK(1221:1221):(1:1)
            java     0 [000]     0.000000: PERF_RECORD_COMM: java:1221/1221
            java     0 [000]     0.000000: PERF_RECORD_FORK(1221:1225):(1221:1221)
            java     0 [000]     0.000000: PERF_RECORD_COMM: java:1221/1225
            java     0 [000]     0.000000: PERF_RECORD_FORK(1221:1232):(1221:1221)
            java     0 [000]     0.000000: PERF_RECORD_COMM: java:1221/1232
            java     0 [000]     0.000000: PERF_RECORD_FORK(1221:1233):(1221:1221)
            java     0 [000]     0.000000: PERF_RECORD_COMM: java:1221/1233
            java     0 [000]     0.000000: PERF_RECORD_FORK(1221:1234):(1221:1221)
            java     0 [000]     0.000000: PERF_RECORD_COMM: java:1221/1234
            java     0 [000]     0.000000: PERF_RECORD_FORK(1221:1235):(1221:1221)
            java     0 [000]     0.000000: PERF_RECORD_COMM: java:1221/1235
            java     0 [000]     0.000000: PERF_RECORD_FORK(1221:1237):(1221:1221)
            java     0 [000]     0.000000: PERF_RECORD_COMM: java:1221/1237
            java     0 [000]     0.000000: PERF_RECORD_FORK(1221:1240):(1221:1221)
            java     0 [000]     0.000000: PERF_RECORD_COMM: java:1221/1240
            java     0 [000]     0.000000: PERF_RECORD_FORK(1221:1241):(1221:1221)
            java     0 [000]     0.000000: PERF_RECORD_COMM: java:1221/1241
            java     0 [000]     0.000000: PERF_RECORD_FORK(1221:1242):(1221:1221)
            java     0 [000]     0.000000: PERF_RECORD_COMM: java:1221/1242
            java     0 [000]     0.000000: PERF_RECORD_FORK(1221:1243):(1221:1221)
            java     0 [000]     0.000000: PERF_RECORD_COMM: java:1221/1243
            java     0 [000]     0.000000: PERF_RECORD_FORK(1221:1244):(1221:1221)
            java     0 [000]     0.000000: PERF_RECORD_COMM: java:1221/1244
            java     0 [000]     0.000000: PERF_RECORD_FORK(1221:1245):(1221:1221)
```
