### ISSUE TITLE
Any ideas to support riscv architecture?

### ISSUE THREAD

**Issue by majin2020** [facebookincubator/BOLT#304]
I have encountered the need to use BOLT on machines with riscv architecture. Is there any plan to support riscv?

**Comment by maksfb** [comment]
I'm not aware of any plans. You can try asking via official BOLT channels on discord/discourse.

**Comment by aaupov** [comment]
CC @preames

**Comment by preames** [comment]
Just for clarity, I was asking about basic scoping for a RISC-V target for BOLT which is why I got tagged, but I'm not planning any work on this in the immediate future.

**Comment by aaupov** [comment]
Testing and reviews are appreciated: https://reviews.llvm.org/D145687

**Comment by aaupov** [comment]
The support was added by Job Noorman.
