### ISSUE TITLE
perf PMU error

### ISSUE THREAD

**Issue by wutzi15** [facebookincubator/BOLT#34]
I've tried on it on differen machines, but when I run the perf command as given in the readme I get the following error:
`sudo perf record -e cycles:u -j any,u -o perf.data -- ls -als`
`Error:`
`PMU Hardware doesn't support sampling/overflow-interrupts.`

It doesn't make a difference if I run it with sudo or without. 
It only works if I run it without `-j any,u`, but then bolt does not work.
Any ideas?

**Comment by xiaoxiao-luomu** [comment]
@maksfb In docker, perf with -j any,u doesn't work too.  which cause it, linux kernel version or hardware?
if I pass -nl option to perf2bolt, then it will take performance improvment?

**Comment by maksfb** [comment]
If `perf` with cycles works, then `-nl` should be able to improve the performance. If `perf` doesn't work, try https://github.com/facebookincubator/BOLT#with-instrumentation-experimental.

**Comment by xiaoxiao-luomu** [comment]
@maksfb I also meet this problem when running "sudo perf record -e cycles:u -j any,u -o perf.data -- ls -als" with -j in vm. how to know it is caused by vm or hardware ? if I change another hardware, it will be ok?

**Comment by maksfb** [comment]
It depends on the hardware. Most CPUs from Intel should support LBRs (`-j` flag).
