### ISSUE TITLE
BOLT bug with -inline-small-functios causes rbp to not be 16 byte aligned

### ISSUE THREAD

**Issue by tmsri** [facebookincubator/BOLT#35]
This bug has happened in a couple of binaries where we see a segfault because an aligned vector insn like movaps, movdqa is accessing a non-aligned address offset of rbp.  This always happens with -inline-small-functions.  On further investigation, I noticed this code sequence in the middle of a function:

0000000003071980 <some_func>:
 3071980:       55                      push   %rbp
 3071981:       48 89 e5                mov    %rsp,%rbp
 3071984:       41 57                   push   %r15
 3071986:       41 56                   push   %r14
 3071988:       41 55                   push   %r13
 307198a:       41 54                   push   %r12
 307198c:       53                      push   %rbx
 307198d:       48 81 ec b8 00 00 00    sub    $0xb8,%rsp
 ...
 307199d:       48 89 fb                mov    %rdi,%rbx
 30719a0:       4c 8d ad 20 ff ff ff    lea    -0xe0(%rbp),%r13
 30719a7:       4c 89 ef                mov    %r13,%rdi
 30719aa:       4c 89 c6                mov    %r8,%rsi
 30719ad:       e8 6e 54 fd ff          callq  3046e20
 30719b2:       4c 89 ef                mov    %r13,%rdi
 30719b5:       55                      push   %rbp
 30719b6:       48 89 e5                mov    %rsp,%rbp
 30719b9:       be 38 1e f3 01          mov    $0x1f31e38,%esi
 30719be:       ba 48 1e f3 01          mov    $0x1f31e48,%edx
 30719c3:       e8 38 53 fe ff          callq  3056d00 
 30719c8:       5d                      pop    %rbp

Notice the insn in 30791b5 and 30719c8. There is no need to spill rbp in the caller as it is callee-saved.  This points to not cleaning up the code after inlining a function.  This is corrupting rbp as it is not 16 byte aligned and the function at 3056d00 is using movaps to access 0xd0(%rbp) and segfaulting.

**Comment by maksfb** [comment]
Thanks for reporting. Inlining in its current form is experimental, and has a lot of potential for improvement.

**Comment by maksfb** [comment]
This should be fixed in the new inliner implementation.
