### ISSUE TITLE
Is BOLT designed to be capable of optimizing static binaries written in languages other than C or C++?

### ISSUE THREAD

**Issue by bstrie** [facebookincubator/BOLT#41]
Quoting from the readme:

> BOLT disassembles functions and reconstructs the control flow graph (CFG) before it runs optimizations. Since this is a nontrivial task, especially when indirect branches are present, we rely on certain heuristics to accomplish it. These heuristics have been tested on a code generated with Clang and GCC compilers.

From the paper:

> one  of  the main challenges with AutoFDO is to map the profile data, collected at the binary level, back to the compiler’s intermediate representation

1. How many of these transformation heuristics are likely to be specific to C/C++?

2. Is the IR that BOLT reconstructs independent of the specific IR format used to compile the code in the first place?

In particular I'm interested in how much work it would take in order for BOLT to optimize libraries written in Rust, which is built atop LLVM, deliberately produces LLVM IR that resembles Clang's, and produces static executables that are intended to be transparently consumed by existing C/C++ debugging tools.

**Comment by maksfb** [comment]
1. If Rust uses LLVM for codegen and does not not introduce any assumptions on code placement, then it should be straightforward to use BOLT on such code.

2. Correct. BOLT can optimize code from Clang/LLVM or GCC. ICC in theory should be fine too, except it may inject assembly functions that baffle BOLT.

**Comment by bstrie** [comment]
Thank you!
