### ISSUE TITLE
[Question] Will BOLT be upstreamed into LLVM

### ISSUE THREAD

**Issue by JonasToth** [facebookincubator/BOLT#46]
Question as the title says.
Is there a plan to follow the upstream releases in a predictable manner or similar?

P.S. Thanks for the nice project, I see good performance improvements in my experiments so far!

**Comment by maksfb** [comment]
It mostly depends on the community demand. There is some interest in adding post-link optimizer to LLVM. See this mailing thread for details: http://lists.llvm.org/pipermail/llvm-dev/2018-October/126985.html

While I would love to see BOLT integrated into LLVM family of tools, technically there's no dependency on any particular LLVM version other than for the purpose of building BOLT itself. I.e, once you have BOLT binary, you can optimize code produced by any version of LLVM/Clang.

**Comment by JonasToth** [comment]
I would like to see it in LLVM as well :)

I found it a little cumbersome to build the latest clang for example, because of the switching of revisions (I use the monorepo, so that was a hazzle), the patching of LLVM and so on. That would of course be less problematic if BOLT is part of LLVM and/or the custom patches are upstreamed.
As a contributor to clang myself I could maybe even help there a bit!

**Comment by Romain-Geissler-1A** [comment]
Hi @maksfb,

Upstreaming that in LLVM is quite a big question, and it will certainly need lot of discussions with the LLVM community.

However I guess there are some steps before that involving less steps. I have three questions for you:
 - Do you or Facebook intend to upstream the local LLVM patch you have for now committed in Bolt ?
 - Do you in Facebook use the commit f137ed238db11440f03083b1c88b7ffc0f4af65e from LLVM from 2018, or do you actually use more recent LLVM commit ?
 - If the above question is that you use more recent LLVM commit, do you have any adaptation needed to use the monorepo layout of LLVM rather putting things in llvm/tools/llvm-bolt ?

Note: we are asking all this in the scope of (mabye) trying to deliver bolt as part of our own company toolchain, and potentially using it where possible (we still have some unresolved problems with the different issues @PierreRamoin-1A has been invovled in.

Cheers,
Romain

**Comment by maksfb** [comment]
Hi Romain,

* I don't think by itself, without BOLT, the patch is useful, and thus no plans to commit it standalone.
* Yes, this is the commit we are based on.

Great! Let me know if you need any help. Is there more information available about your toolchain?

Cheers,
Maksim

**Comment by Romain-Geissler-1A** [comment]
Hi,

There is really not bits of this patch which seem useful from an LLVM point of view ? Ok it's not big deal, but we already embed clang as part of our toolchain, obviously a different version, and I was somehow hoping we could avoid building LLVM twice (once for clang/lld, and once for bolt) since we build the first one with PGO + LTO and this is quite long already. And you know, as a developer I usually prefer when we don't duplicate things and upstream patches so that long term maintenance is actually easier since it's maintained by upstream directly.

One day we will open source our toolchain, I already have the legal approval from my employer, I just need to adapt some bits to make it public (ie not depend on Amadeus-only resources like git repositories) which I had no time to do for now. However there is nothing revolutionary in it, many people have set up their own before us, we are mainly following the guidelines from Linux From Scratch. Maybe what is uncommon in our toolchain is that we don't install the glibc in a standard folder, so that we can have several incompatible toolchains in parallel and different processes using them at the same time. It's for now gcc based, but we ship clang as well. We switched recently to using lld instead of bfd/gold (which is a bit strange to combine lld and gcc, usually it goes with clang). We have several versions of our toolchain in parallel, we usually fork one major branch per year, and each year we upgrade to the latest available gcc (so we have one with gcc 6, gcc 8 and gcc 9).

@PierreRamoin-1A will add Bolt in our toolchain, eventually when it will be open source you will be able to see it. Pierre did try Bolt with gcc 6 and 8 during his internship with us.

Cheers,
Romain

**Comment by maksfb** [comment]
Thank you for providing more background and the info on your toolchain.

We have previously upstreamed patches that are useful outside of BOLT scope. We have also upstreamed bug fixes. If there's something we've missed, it would be by an accident. For the rest of the code in the patch, it is hard to justify the inclusion in llvm trunk. Even if we commit the patch, we would not have good test cases without BOLT in the trunk, which will turn into a maintenance headache.

**Comment by Romain-Geissler-1A** [comment]
Hi @maksfb,

I saw your recent proposal sent to the LLVM mailing list about considering an upstreaming. I wonder what will eventually happen and what the Google folks will do with their Propeller alternative.

I contact you as I have just updated the gcc code base in the Amadeus toolchain, to today's gcc master branch. And it happens that now the LLVM code you are based on (LLVM commit f137ed238db11440f03083b1c88b7ffc0f4af65e) can't compile anymore with the latest gcc. I have these error almost immediately in the build:

```
/workdir/src/llvm-old-repo-7.0.0/lib/Demangle/ItaniumDemangle.cpp
/workdir/src/llvm-old-repo-7.0.0/lib/Demangle/ItaniumDemangle.cpp:103:36: error: 'numeric_limits' is not a member of 'std'
  103 |   unsigned CurrentPackIndex = std::numeric_limits<unsigned>::max();
      |                                    ^~~~~~~~~~~~~~
/workdir/src/llvm-old-repo-7.0.0/lib/Demangle/ItaniumDemangle.cpp:103:51: error: expected primary-expression before 'unsigned'
  103 |   unsigned CurrentPackIndex = std::numeric_limits<unsigned>::max();
      |                                                   ^~~~~~~~
/workdir/src/llvm-old-repo-7.0.0/lib/Demangle/ItaniumDemangle.cpp:104:34: error: 'numeric_limits' is not a member of 'std'
  104 |   unsigned CurrentPackMax = std::numeric_limits<unsigned>::max();
      |                                  ^~~~~~~~~~~~~~
/workdir/src/llvm-old-repo-7.0.0/lib/Demangle/ItaniumDemangle.cpp:104:49: error: expected primary-expression before 'unsigned'
  104 |   unsigned CurrentPackMax = std::numeric_limits<unsigned>::max();
      |                                                 ^~~~~~~~
/workdir/src/llvm-old-repo-7.0.0/lib/Demangle/ItaniumDemangle.cpp: In member function 'void {anonymous}::ParameterPack::initializePackExpansion({anonymous}::OutputStream&) const':
/workdir/src/llvm-old-repo-7.0.0/lib/Demangle/ItaniumDemangle.cpp:955:34: error: 'numeric_limits' is not a member of 'std'
  955 |     if (S.CurrentPackMax == std::numeric_limits<unsigned>::max()) {
      |                                  ^~~~~~~~~~~~~~
/workdir/src/llvm-old-repo-7.0.0/lib/Demangle/ItaniumDemangle.cpp:955:49: error: expected primary-expression before 'unsigned'
  955 |     if (S.CurrentPackMax == std::numeric_limits<unsigned>::max()) {
      |                                                 ^~~~~~~~
/workdir/src/llvm-old-repo-7.0.0/lib/Demangle/ItaniumDemangle.cpp:955:49: error: expected ')' before 'unsigned'
/workdir/src/llvm-old-repo-7.0.0/lib/Demangle/ItaniumDemangle.cpp:955:8: note: to match this '('
  955 |     if (S.CurrentPackMax == std::numeric_limits<unsigned>::max()) {
      |        ^
/workdir/src/llvm-old-repo-7.0.0/lib/Demangle/ItaniumDemangle.cpp: In member function 'virtual void {anonymous}::ParameterPackExpansion::printLeft({anonymous}::OutputStream&) const':
/workdir/src/llvm-old-repo-7.0.0/lib/Demangle/ItaniumDemangle.cpp:1038:35: error: 'numeric_limits' is not a member of 'std'
 1038 |     constexpr unsigned Max = std::numeric_limits<unsigned>::max();
      |                                   ^~~~~~~~~~~~~~
/workdir/src/llvm-old-repo-7.0.0/lib/Demangle/ItaniumDemangle.cpp:1038:50: error: expected primary-expression before 'unsigned'
 1038 |     constexpr unsigned Max = std::numeric_limits<unsigned>::max();
      |                                                  ^~~~~~~~
```

while there is no doubt it is trivial to fix (explicitly include <limits> in this file), it shows that the fact you currently base your source code on LLVM 7 will eventually trigger more and more compilation errors with newer compiler/linker/libc. I checked the read me, it still advices to use the commit f137ed238db11440f03083b1c88b7ffc0f4af65e from LLVM 7. Do you think that now that should be rebased on top of a more recent LLVM ? Actually if your upstream merge proposal is accepted, this is something you will most likely need to do ;)

Cheers,
Romain

**Comment by rafaelauler** [comment]
Hi Romain,

Thanks for letting us now. Indeed, I plan on rebasing and I already took a look to assess how much effort will be required. That is definitely in our plans.

Best,
Rafael

**Comment by JonasToth** [comment]
Its in llvm now
