### ISSUE TITLE
Missing info on assumptions/limitations

### ISSUE THREAD

**Issue by amonakov** [facebookincubator/BOLT#5]
The tool consumes post-link binaries. In general, even finding instruction boundaries on x86 isn't exactly solvable, let alone deciding basic block boundaries, safety of reordering, etc. Thus, the tool obviously makes a lot of assumptions about input, or, in other words, has limitations w.r.t which programs can be correctly transformed.

The EuroLLVM'2016 presentation on BOLT has a brief enumeration of (some?) limitations, so evidently the issues were realized, but unfortunately neither the README nor the initial Facebook article make no mention of them.

It would be nice to have a description of the class of programs to which BOLT may be applied safely.

Also, if BOLT implementation has built-in safeguards for deciding "can't touch this code", it would be nice to know how they operate, too.

**Comment by maksfb** [comment]
It's a really good suggestion. Thank you. We'll add the detailed requirements.

**Comment by maksfb** [comment]
The README now lists general input binary requirements. If you have specific questions please let me know.
