### ISSUE TITLE
[libcurl] Commit 76b9790 leads to assertion failure

### ISSUE THREAD

**Issue by PierreRamoin-1A** [facebookincubator/BOLT#56]
After updated BOLT to 76b97902edd63b9e9ec516ebb8257f021993045b, I have an assertion failure when I try to apply BOLT on a binary including ```libcurl.a```. Here is the assertion:

```
llvm-bolt: /home/cloud-user/repo/llvm/tools/llvm-bolt/src/BinaryContext.cpp:265: 
std::pair<llvm::bolt::JumpTable*, const llvm::MCSymbol*>
llvm::bolt::BinaryContext::createJumpTable(llvm::bolt::BinaryFunction&, uint64_t, llvm::bolt::JumpTable::JumpTableType, llvm::bolt::JumpTable::OffsetEntriesType&&): 
Assertion `JT->Parent == &Function && "cannot re-use jump table of a different function"' failed.
```
 
It occurs when BOLT is processing ```curl_multi_strerror``` as function and ```curl_easy_strerror``` as parent.

To reproduce you can either apply BOLT on the shared libcurl, or compile this small program  with the static version of libcurl:

```
#include <curl.h>

int main() {
  curl_easy_init();
  return 0;
}
```

For what I saw, this assertion wasn't present on the previous commit, and BOLT was finishing with no warning or error.

**Comment by maksfb** [comment]
Thank you for reporting the problem. I couldn't reproduce using the version of `libcurl.a` that I have. Could you upload the binary?

**Comment by PierreRamoin-1A** [comment]
Here it is:

[libcurl.zip](https://github.com/facebookincubator/BOLT/files/3213003/libcurl.zip)

**Comment by maksfb** [comment]
Thanks.  I have an upcoming change to the way we handle jump tables for position-independent code that should fix this.

**Comment by PierreRamoin-1A** [comment]
I saw the commit 3ecda6eccb6873395ce27d2e32269c997303526e was talking about jump tables, but I don't know if it is the upcoming change you talked about.
If it is, I still have the problem with this patch, even on 32f147aee17bfd743ec4e3bfe85f8361ae13eaeb

**Comment by maksfb** [comment]
No, sorry, the diff I was talking about isn't out yet.
