### ISSUE TITLE
llvm-bolt crashes with a seg fault

### ISSUE THREAD

**Issue by railkar** [facebookincubator/BOLT#58]
Summary: After adding -print-all to the llvm-bolt command arguments, it crashes.

Command that does not crash:
llvm-bolt memcached -o memcached.bolt -data=lbr.fdata -reorder-blocks=cache+ -reorder-functions=hfsort+ -split-functions=3 -split-all-cold -split-eh -dyno-stats -print-profile-stats -print-cache-metrics -report-stale -v=1

Add: -print-all to the command above
Result: Crash
Please see .fdata file and the memcached executable (attached tarball) to reproduce the issue.

Stack dump is as follows:
LLVMSymbolizer: error reading file: No such file or directory
#0 0x0000000000eea11a (llvm-bolt+0xeea11a)
#1 0x0000000000ee82ae (llvm-bolt+0xee82ae)
#2 0x0000000000ee83fc (llvm-bolt+0xee83fc)
#3 0x00007f2c592ec390 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11390)
#4 0x0000000000508b46 (llvm-bolt+0x508b46)
#5 0x00000000004bc128 (llvm-bolt+0x4bc128)
#6 0x00000000004d318b (llvm-bolt+0x4d318b)
#7 0x00000000004d5807 (llvm-bolt+0x4d5807)
#8 0x0000000000531d13 (llvm-bolt+0x531d13)
#9 0x00000000005735a1 (llvm-bolt+0x5735a1)
#10 0x00000000005736a5 (llvm-bolt+0x5736a5)
#11 0x000000000042d4cc (llvm-bolt+0x42d4cc)
#12 0x00007f2c58049830 __libc_start_main /build/glibc-LK5gWL/glibc-2.23/csu/../csu/libc-start.c:325:0
#13 0x000000000047cec9 (llvm-bolt+0x47cec9)
Stack dump:
0.	Program arguments: llvm-bolt memcached -o memcached.bolt -data=lbr.fdata -reorder-blocks=cache+ -reorder-functions=hfsort+ -split-functions=3 -split-all-cold -split-eh -dyno-stats -print-profile-stats -print-cache-metrics -report-stale -v=1 -print-all 
Segmentation fault (core dumped)

Note: I renamed the tarball (.tgz) to .zip to satisfy the file uploader

[bolt-crash.zip](https://github.com/facebookincubator/BOLT/files/3419447/bolt-crash.zip)

**Comment by maksfb** [comment]
Thank you for the bug report. Is your `llvm-bolt` compiled with assertions? I'm getting one triggered locally even using the command that does not crash for you.

**Comment by railkar** [comment]
cmake -G Ninja ../llvm -DLLVM_TARGETS_TO_BUILD="X86;AArch64" -DCMAKE_BUILD_TYPE=Release
ninja

I simply followed the instructions on the github page to build the llvm-bolt binary.

**Comment by maksfb** [comment]
I'm not sure if it is "the issue", but once I disable assertions I'm hitting a problem with the printout.

**Comment by maksfb** [comment]
If the last valid printout is "after lower-annotations", then it's the issue with printing profile info for conditional tail calls without annotations.

**Comment by maksfb** [comment]
To check if that's the problem, you can add `-simplify-conditional-tail-calls=0` option and see if it goes away.

**Comment by railkar** [comment]
Adding -simplify-conditional-tail-calls=0 makes it go away. Thanks. Is this a bug though in the printing part of the code?

**Comment by maksfb** [comment]
The problem is that `getDynoStats()` cannot properly handle conditional tail calls since annotations are removed.

**Comment by railkar** [comment]
OK, so I can confirm that -dyno-stats and -print-all are incompatible when -simplify-conditional-tail-calls=1
