### ISSUE TITLE
[Compilation] AArch64 target mandatory

### ISSUE THREAD

**Issue by PierreRamoin-1A** [facebookincubator/BOLT#59]
Hi,
The actual BOLT compilation requires to enable the LLVM AArch64 target.
Otherwise I face this error:
```ld: cannot find -lLLVMBOLTTargetAArch64```

Is there a specific reason not to adapt to LLVM CMake configuration, and build only the required targets?

Thanks,
Pierre

**Comment by rafaelauler** [comment]
It would be nice to fix this indeed, it will require a little bit of refactoring.
