### ISSUE TITLE
Can we optimize android applications with BOLT?

### ISSUE THREAD

**Issue by bosepriy** [facebookincubator/BOLT#62]
Hi,

I would like to optimize some android apps with our x86 arch but would like some support with regards to better understanding/
I have generated some perf.data based on the BKM suggested by README of BOLT.
This perf.data which I collected  has binary data not specific to any particular binary/module running on the aosp. It has data related to libart,libc and other android modules triggered while executing that app. 
So if i now try to generate bolt optimized binary with "llvm-bolt" . Can i just use the specific aosp module that is having issues and generate only with  particular executable (like for eg libc.so if that's the problematic one) :
=> llvm-bolt libc.so -o libc.bolt -data=perf.fdata ....

Will this generate bolt optimized binary "libc.bolt"  or do i need to use it in some other way ?

Regards,
Priyanka

**Comment by maksfb** [comment]
When you convert `perf.data` into `perf.fdata` using `perf2bolt` utility, you have to pass the binary name. `perf2bolt` will only convert events corresponding to that binary. In other words, while `perf.data` has aggregated profile for all binaries, `perf.fdata` is binary-specific.

Note that we haven't tested BOLT on android yet.

**Comment by bosepriy** [comment]
Ok thanks for the information
