### ISSUE TITLE
perf2bolt issue: cannot find BB containing branch destination

### ISSUE THREAD

**Issue by rlavaee** [facebookincubator/BOLT#64]
Hi,
The upstream perf2bolt fails on clang bootstrap with the following error (This error does not occur when using perf2bolt from **d38c5913e33bf2e61bba7b2a729bfc4aee8f6129**)

/usr/local/google/home/rahmanl/copt/build/BOLT/release/bin/perf2bolt -o pgo-relocs.fdata -w pgo-relocs-compiler.yaml -p pgo-relocs.perfdata /usr/local/google/home/rahmanl/copt/source/llvm-propeller/plo/pgo-relocs/build/bin/clang-10
PERF2BOLT: Starting data aggregation job for pgo-relocs.perfdata
PERF2BOLT: spawning perf job to read branch events
PERF2BOLT: spawning perf job to read mem events
PERF2BOLT: spawning perf job to read process events
PERF2BOLT: spawning perf job to read task events
BOLT-INFO: Target architecture: x86_64
BOLT-INFO: first alloc address is 0x200000
BOLT-INFO: creating new program header table at address 0x4a00000, offset 0x4800000
BOLT-INFO: enabling relocation mode
BOLT-WARNING: build-id will not be checked because we could not read one from input binary
BOLT-INFO: enabling strict relocation mode for aggregtion purposes
BOLT-INFO: spawning thread to pre-process profile
PERF2BOLT: waiting for perf mmap events collection to finish...
PERF2BOLT: parsing perf-script mmap events output
PERF2BOLT: waiting for perf task events collection to finish...
PERF2BOLT: parsing perf-script task events output
BOLT-ERROR: cannot find BB containing branch destination.
=======================================
BOLT is unable to proceed because it couldn't properly understand this function.
If you are running the most recent version of BOLT, you may want to report this and paste this dump.
Please check that there is no sensitive contents being shared in this dump.

Offending function: _ZN4llvm13X86AsmPrinter18EmitSEHInstructionEPKNS_12MachineInstrE/X86MCInstLower.cpp/1(*2)

Function contents (
  0000: 80BF1003 00000074 2B488B87 80000000  |.......t+H......|
  0010: 488B7810 488B4610 B923FFFF FF03080F  |H.x.H.F..#......|
  0020: B7C1FF24 C588AC89 00488B07 488B4058  |...$.....H..H.@X|
  0030: 31F6FFE0 488B4610 B923FFFF FF03080F  |1...H.F..#......|
  0040: B7C1FF24 C5D0AC89 00488BBF 80000000  |...$.....H......|
  0050: 488B0748 8B80F803 000031F6 FFE0488B  |H..H......1...H.|
  0060: 46208B70 10488B07 488B8080 00000031  |F .p.H..H......1|
  0070: D2FFE048 8B46208B 7010488B 07488B40  |...H.F .p.H..H.@|
  0080: 7031D2FF E0488B46 208B7010 488B0748  |p1...H.F .p.H..H|
  0090: 8B808800 000031D2 FFE0488B 46208B70  |......1...H.F .p|
  00A0: 10488B07 488B4078 31D2FFE0 488BBF80  |.H..H.@x1...H...|
  00B0: 00000048 8B46208B 70108B50 30488B07  |...H.F .p..P0H..|
  00C0: 488B80E0 03000031 C9FFE048 8BBF8000  |H......1...H....|
  00D0: 0000488B 46208B70 10488B07 488B80C8  |..H.F .p.H..H...|
  00E0: 03000031 D2FFE048 8BBF8000 0000488B  |...1...H......H.|
  00F0: 462031F6 48837810 00400F95 C6488B07  |F 1.H.x..@...H..|
  0100: 488B80F0 03000031 D2FFE048 8BBF8000  |H......1...H....|
  0110: 0000488B 46208B70 108B5030 488B0748  |..H.F .p..P0H..H|
  0120: 8B80E803 000031C9 FFE0488B BF800000  |......1...H.....|
  0130: 00488B46 208B7010 8B503048 8B07488B  |.H.F .p..P0H..H.|
  0140: 80D00300 0031C9FF E0488BBF 80000000  |.....1...H......|
  0150: 488B4620 8B701048 8B07488B 80D80300  |H.F .p.H..H.....|
  0160: 0031D2FF E0CCCCCC CCCCCCCC CCCCCCCC  |.1..............|
)

Binary Function "_ZN4llvm13X86AsmPrinter18EmitSEHInstructionEPKNS_12MachineInstrE/X86MCInstLower.cpp/1(*2)"  {
  Other names : _ZN4llvm13X86AsmPrinter18EmitSEHInstructionEPKNS_12MachineInstrE/1
  Number      : 120
  State       : disassembled
  Address     : 0x153d890
  Size        : 0x165
  MaxSize     : 0x170
  Offset      : 0x133c890
  Section     : .text
  Orc Section : .local.text._ZN4llvm13X86AsmPrinter18EmitSEHInstructionEPKNS_12MachineInstrE/1
  LSDA        : 0x0
  IsSimple    : 1
  IsSplit     : 0
  BB Count    : 15
}
Jump table JUMP_TABLE/_ZN4llvm13X86AsmPrinter18EmitSEHInstructionEPKNS_12MachineInstrE/1.0 for function _ZN4llvm13X86AsmPrinter18EmitSEHInstructionEPKNS_12MachineInstrE/X86MCInstLower.cpp/1(*2) at 0x89ac88 with a total count of 0:
  0x0000 : .Ltmp93
  0x0008 : .Lfunc_end1
  0x0010 : .Lfunc_end1
  0x0018 : .Ltmp94
  0x0020 : .Lfunc_end1
  0x0028 : .Lfunc_end1
  0x0030 : .Ltmp95
  0x0038 : .Ltmp96
  0x0040 : .Ltmp97

Jump table JUMP_TABLE/_ZN4llvm13X86AsmPrinter18EmitSEHInstructionEPKNS_12MachineInstrE/1.1 for function _ZN4llvm13X86AsmPrinter18EmitSEHInstructionEPKNS_12MachineInstrE/X86MCInstLower.cpp/1(*2) at 0x89acd0 with a total count of 0:
  0x0000 : .Ltmp98
  0x0008 : .Lfunc_end1
  0x0010 : .Ltmp99
  0x0018 : .Ltmp100
  0x0020 : .Ltmp101
  0x0028 : .Ltmp102
  0x0030 : .Ltmp103
  0x0038 : .Lfunc_end1
  0x0040 : .Ltmp104

DWARF CFI Instructions:
    <empty>
End of Function "_ZN4llvm13X86AsmPrinter18EmitSEHInstructionEPKNS_12MachineInstrE/X86MCInstLower.cpp/1(*2)"

ERROR: disassembly failed - inconsistent branch found.
=======================================
pure virtual method called
terminate called without an active exception
pure virtual method called
terminate called recursively

**Comment by maksfb** [comment]
Hi Rahman, thanks for reporting. I couldn't easily bootstrap the latest clang. Could you share the binary?

**Comment by rlavaee** [comment]
Thanks @maksfb. Actually, I figured I did not have the upstream version. A new problem is introduced now. I close this issue and open a new one.
