### ISSUE TITLE
perf2bolt cannot map the binary name to profile.

### ISSUE THREAD

**Issue by rlavaee** [facebookincubator/BOLT#65]
When bolting clang-10 (githash: d694594d76505), perf2bolt fails as follows and does not process the profile.

perf2bolt -o pgo-relocs.fdata -w pgo-relocs-compiler.yaml -p pgo-relocs.perfdata clang-10
PERF2BOLT: Starting data aggregation job for pgo-relocs.perfdata
PERF2BOLT: spawning perf job to read branch events
PERF2BOLT: spawning perf job to read mem events
PERF2BOLT: spawning perf job to read process events
PERF2BOLT: spawning perf job to read task events
BOLT-INFO: Target architecture: x86_64
BOLT-INFO: first alloc address is 0x200000
BOLT-INFO: creating new program header table at address 0x4c00000, offset 0x4a00000
BOLT-INFO: enabling relocation mode
BOLT-WARNING: build-id will not be checked because we could not read one from input binary
BOLT-INFO: enabling strict relocation mode for aggregation purposes
BOLT-INFO: spawning thread to pre-process profile
PERF2BOLT: waiting for perf mmap events collection to finish...
PERF2BOLT: parsing perf-script mmap events output
PERF2BOLT-WARNING: ignoring mapping of clang-10 at 0x1518000
....
.....
PERF2BOLT-ERROR: could not find a profile matching binary "clang-10". Profile for the following binary name(s) is available:
  bash
  clang-10
  head
  ld-2.28.so
  libc-2.28.so
  libdl-2.28.so
  libgcc_s.so.1
  libm-2.28.so
  libpthread-2.28.so
  librt-2.28.so
  libstdc++.so.6.0.25
  libtinfo.so.6.1
  libz.so.1.2.11
  xargs
Please rename the input binary.

**Comment by nlbrown2** [comment]
When I go through the steps on Optimizing Clang With Bolt, I also run into this issue. For me, I am optimizing clang-7. Before I get the error output that it could not find a profile matching clang-7 and the list of binaries it has profile information for, I get many warnings saying it is skipping a mapping for clang-7. 
`PERF2BOLT-WARNING: ignoring mapping of clang-7 at 0x136c000`                                                    is printed on my screen easily 1000 times. I am unsure of how to tell `perf2bolt` to not ignore this mapping.
