### ISSUE TITLE
No performance improvement in AArch64 target

### ISSUE THREAD

**Issue by meghendra6** [facebookincubator/BOLT#68]
I have applied bolt to small binary in AArch64.
However there is no performance improvement.

Source code is very simple and light.

```
#include <stdio.h>
#include <stdlib.h>
#include <sys/time.h>
#define ARRAY_LEN 30000

static struct timeval tm1;

static inline void start() {
    gettimeofday(&tm1, NULL);
}

static inline void stop() {
    struct timeval tm2;
    gettimeofday(&tm2, NULL);
    unsigned long long t = 1000 * (tm2.tv_sec - tm1.tv_sec) +\
                           (tm2.tv_usec - tm1.tv_usec) / 1000;
    printf("%llu ms\n", t);
}

void bubble_sort (int *a, int n) {
    int i, t, s = 1;
    while (s) {
        s = 0;
        for (i = 1; i < n; i++) {
            if (a[i] < a[i - 1]) {
                t = a[i];
                a[i] = a[i - 1];
                a[i - 1] = t;
                s = 1;
            }
        }
    }
}

void sort_array() {
    printf("Bubble sorting array of %d elements\n", ARRAY_LEN);
    int data[ARRAY_LEN], i;
    for(i=0; i<ARRAY_LEN; ++i){
        data[i] = rand();
    }
    bubble_sort(data, ARRAY_LEN);
}

int main(){
    start();
    sort_array();
    stop();
    return 0;
}
```

Note that profiling data from AArch64 does not include LBR.
On x86, I added the '-nl align-macro-fusion = none' option to test the same environment as AArch64 using the above source code. But it worked without any problems.

Can you tell me why it doesn't work with AArch64?

**Comment by maksfb** [comment]
BOLT improves the performance of applications suffering from high instruction cache and iTLB miss rates. If the application is small, like the example above that fits into the instruction cache, then there's no benefit in using BOLT.

On x86-64 there's an exception to this rule, where BOLT can improve the performance via better alignment for allowing macro-op fusion. I've seen it happening for a small benchmark where the benchmark had a misaligned macro-op pair in a hot loop.
