### ISSUE TITLE
perf2bolt segfaults when applied to clang-7

### ISSUE THREAD

**Issue by nlbrown2** [facebookincubator/BOLT#70]
When applying perf2bolt to clang-7 for another workload, I run into a segfault within `std::vector::push_back` (the value for "this" is 0x18). However, I believe it is because `BinaryBasicBlock::addSuccessor` is passed a `nullptr` for `Succ`. The value for `Succ` is generated by a call to `BinaryFunction::getBasicBlockForLabel` (see `BinaryFunction.cpp:1611` for the call site). I am not sure how to ensure the basic block for this label can be found. If it makes a difference, the profile data is being collected via `perf record -e cycles:u -j any,u -- bash compile.sh`, then applied with `perf2bolt $(which clang-7) -p perf.data -o clang-7.fdata -w clang-7.yaml`

**Comment by maksfb** [comment]
Where is `clang-7` coming from? Did you build it yourself or is it a part of a standard distribution?

**Comment by nlbrown2** [comment]
It is the same one used in the Optimizing Clang steps. It is custom built with "-Wl,-q"

**Comment by maksfb** [comment]
Are you running `llvm-bolt` on bootstrapped Clang from Stage 2 or on Clang from Stage 1?

**Comment by nlbrown2** [comment]
Stage 1. I'll try stage 2 and see if the problem persists

**Comment by nlbrown2** [comment]
Using stage 2 (`stage2-prof-use-lto/install/bin/clang`) appears to have worked. Do you happen to know why and/or if it is possible to apply bolt to non-pgo/lto-ed versions of clang?

**Comment by maksfb** [comment]
Most likely you are building Stage 1 with GCC 8 or later, and you need `-fno-reorder-blocks-and-partition` for BOLT to work. Stage 2 is built with Clang, hence there's no problem.

**Comment by nlbrown2** [comment]
Understood. Thank you!
