### ISSUE TITLE
Build instructions aren't exactly right

### ISSUE THREAD

**Issue by jwbee** [facebookincubator/BOLT#71]
The readme says to cmake ../llvm, but it should be just cmake ..

-jwb

**Comment by maksfb** [comment]
The `cmake` command is issued from the `build` directory which is a sibling of `llvm` directory. Hence `../llvm` as a source path.

BTW, we also have a Docker file at https://github.com/facebookincubator/BOLT/blob/master/utils/docker/Dockerfile which might help you with the build.
