### ISSUE TITLE
Trouble running perf when following README instructions.

### ISSUE THREAD

**Issue by proyan** [facebookincubator/BOLT#72]
Hi guys,

Kudos for this application. 
I tried to follow the guidelines provided in your Readme file for optimizing my performance. When I ran 
```
sudo perf record -e cycles:u -j any,u -o perf.data -- <exec-name>
```
I get the error that 
```
Workload failed: No such file or directory
```

I tried to look online what the issue was, and apparently I'm not giving the correct command to the profiler. Your Readme mentions that perf > 4.5 should be preferred.

When I run `perf --version`, I get `perf version 4.10.17`. However, `perf -F brstack` command doesn't exist in this version (or I wasn't able to find it). I installed perf by `apt install linux-tools-$(uname -r)` option.

However, I'm no expert on `perf`. Help on this issue would be appreciated.

Best,
Rohan

EDIT:

I ran `perf report` on the generated `perf.data` file. This is the output of the command:

```
Warning:
Kernel address maps (/proc/{kallsyms,modules}) were restricted.
Check /proc/sys/kernel/kptr_restrict before running 'perf record'.
As no suitable kallsyms nor vmlinux was found, kernel samples can't be resolved.                                                Samples in kernel modules can't be resolved as well.
```

I checked `kptr_restrict`, and it is set to zero.

```
cat  /proc/sys/kernel/kptr_restrict
0
```

**Comment by maksfb** [comment]
The most common case for the `Workload failed: No such file or directory` error is an invalid `<exec-name>`, i.e. `perf` is unable to execute the binary. Do you have the right permissions? Note that you are trying to run the command as `root`, i.e. you should check that `sudo <exec-name>` works.

Could you check if `perf help script` mentions `-F` flag? If not, could you tell what Linux distribution you are running?

**Comment by proyan** [comment]
Hi @maksfb 
Thanks for the help. It was indeed a permissions problem.

I managed to find the `-F` flag inside the `perf help script`. All is good :)
I'll close this issue.
