### ISSUE TITLE
LLVM ERROR: Undefined temporary symbol from llvm-bolt

### ISSUE THREAD

**Issue by uttampawar** [facebookincubator/BOLT#74]
Hi,
I encountered another error while using llvm-bolt program.

Environment:
LLVM (http://llvm.org/):
  LLVM version 7.0.0svn
  DEBUG build with assertions.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: skylake-avx512

BOLT revision f137ed238db11440f03083b1c88b7ffc0f4af65e

GCC: gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)

On running,
 llvm-bolt /tmp/a.out  -o ./a.out.bolt  -data=./perf.fdata  -use-gnu-stack -dyno-stats -icf=1  -reorder-blocks=cache+ -split-functions=3 -split-all-cold -v1=1

...
BOLT-INFO: program-wide dynostats after all optimizations before SCTC and FOP:

            43609914 : executed forward branches
             4245029 : taken forward branches
            13263040 : executed backward branches
            10701987 : taken backward branches
             1818639 : executed unconditional branches
             6881785 : all function calls
              557180 : indirect calls
              428234 : PLT calls
           375782056 : executed instructions
            92966230 : executed load instructions
            48237455 : executed store instructions
             4576084 : taken jump table branches
            58691593 : total branches
            16765655 : taken branches
            41925938 : non-taken conditional branches
            14947016 : taken conditional branches
            56872954 : all conditional branches

            45232650 : executed forward branches (+3.7%)
             1028212 : taken forward branches (-75.8%)
            11640304 : executed backward branches (-12.2%)
             8449855 : taken backward branches (-21.0%)
             1848804 : executed unconditional branches (+1.7%)
             6881785 : all function calls (=)
              557180 : indirect calls (=)
              428234 : PLT calls (=)
           378762345 : executed instructions (+0.8%)
            92966230 : executed load instructions (=)
            48237455 : executed store instructions (=)
             4576084 : taken jump table branches (=)
            58721758 : total branches (+0.1%)
            11326871 : taken branches (-32.4%)
            47394887 : non-taken conditional branches (+13.0%)
             9478067 : taken conditional branches (-36.6%)
            56872954 : all conditional branches (=)

BOLT-INFO: Finished pass: print dyno-stats after optimizations
BOLT-INFO: Starting pass: simplify-conditional-tail-calls
BOLT-INFO: SCTC: patched 419 tail calls (416 forward) tail calls (3 backward) from a total of 419 while removing 7 double jumps and removing 392 basic blocks totalling 2123 bytes of code. CTCs total execution count is 80880 and the number of times CTCs are taken is 76505.
BOLT-INFO: Finished pass: simplify-conditional-tail-calls
BOLT-INFO: Starting pass: aligner
BOLT-INFO: Finished pass: aligner
BOLT-INFO: Starting pass: reorder-data
BOLT-INFO: Finished pass: reorder-data
BOLT-INFO: Starting pass: finalize-functions
BOLT-INFO: Finished pass: finalize-functions
BOLT-INFO: Starting pass: frame-optimizer
BOLT-INFO: Finished pass: frame-optimizer
BOLT-INFO: Starting pass: alloc-combiner
BOLT-INFO: Finished pass: alloc-combiner
BOLT-INFO: Starting pass: retpoline-insertion
BOLT-INFO: Finished pass: retpoline-insertion
BOLT-INFO: Starting pass: inst-lowering
BOLT-INFO: Finished pass: inst-lowering
BOLT-INFO: Starting pass: lower-annotations
BOLT-INFO: Finished pass: lower-annotations
LLVM ERROR: Undefined temporary symbol

I tried to apply suggested workarounds after referring to few similar issues reported earlier such as use of "-eliminate-unreachable=0".
I still get the same LLVM-ERROR: Undefined temporary symbol
..
BOLT-INFO: Starting pass: inst-lowering
BOLT-INFO: Finished pass: inst-lowering
BOLT-INFO: Starting pass: lower-annotations
BOLT-INFO: Finished pass: lower-annotations
LLVM ERROR: Undefined temporary symbol

With use of errs() in computeSymbol() function, I get symbol name as,
MCSymbol: '.Ltmp271994' isDefined=0 isExternal=0 isTemporary=1

I don't know how to proceed from here.

**Comment by maksfb** [comment]
Are you using `-freorder-blocks-and-partition` option when compiling with GCC? If yes, could you try the latest BOLT?
