### ISSUE TITLE
[Question] Update patch to use with latest stable llvm 9.0 and upcoming 10?

### ISSUE THREAD

**Issue by Lorac** [facebookincubator/BOLT#80]
I would like to introduce BOLT inside the Yocto project, but they always use the latest stable of the software. Since BOLT seems to be on version 7.0 of llvm which makes it rather difficult/impossible to use it inside Yocto.

I see that the development is still pretty active and I am thrilled to be able to use the tool, but I would like to know if there is any plan to keep pace with the llvm project stable releases?

**Comment by aaupov** [comment]
Hi @Lorac! We've rebased BOLT and now following LLVM's main branch, so I'm closing this issue as resolved.
