### ISSUE TITLE
[Question] Does BOLT layout hot bbs from all functions together?

### ISSUE THREAD

**Issue by miz2019** [facebookincubator/BOLT#84]
From SplitFunctions.cpp, I see hot bbs are splitted from cold bbs and placed  as hot  followed by code ones **in a function.**  however, I did not found logic to collect all hot bbs across function together. As which I think could further boost performance. Did I missed something?

Enabling such layout could break jump ranges of some branch insts,  trampoline or inst replacement(short range to long ones) may be needed.

Thanks.

**Comment by rafaelauler** [comment]
The function emission stage (emitFunctions() - emitFunction() and helpers) is when layout happens, and this logic is gated under "cold" being false or true. See
https://github.com/facebookincubator/BOLT/blob/bf70145cc29d3b609fd799dda9ff7c92a3439bc0/src/BinaryEmitter.cpp#L267

Depending on this value, we instruct the streamer (from the LLVM's integrated assembler libs) to emit instructions to either a "hot" section or a "cold" one. The final layout achieves an effective separation where hot code is all clustered together with no cold code in between.
See https://github.com/facebookincubator/BOLT/blob/bf70145cc29d3b609fd799dda9ff7c92a3439bc0/src/BinaryEmitter.cpp#L277

Regarding the challenges of doing this, for some architectures, such as ARM, it does indeed break ranges. Similar to how a linker also needs to deal with relaxing ranges, we provide a similar step to extend branches ranges here
https://github.com/facebookincubator/BOLT/blob/084b44c744b339f32245ed049900c0c2966a206f/src/Passes/LongJmp.h#L34

Jump tables in x86 PIC code typically address an entire +-2GB memory range from the jumptable location itself and don't need to be handled specially in the most common linking mode (which doesn't use the large code model). In non-PIC mode, each entry of the jump table is able to address the entire virtual address space (8-byte pointers).

Jump table entries in ARM are encoded using an offset from the end of the basic block where the indirect branch is. ARM support is experimental and we don't support rearranging this case right now. To allow us to move forward with rewriting ARM binaries in this case, we just "freeze" a function that has this indirect branch and don't move anything in it, but still change its placement relative to other functions.

Regarding direct jump instructions relaxation, where the target address is encoded in the instruction itself, the LLVM streamer (the assembler component) does this step for us.

**Comment by miz2019** [comment]
Very clear, thank you for your detailed explanation, rafaelauler. 
Surprisely find you are the author of a favorite llvm book. :)

**Comment by rafaelauler** [comment]
You're welcome! Glad you liked it
