### ISSUE TITLE
No .rela.text section in ELF

### ISSUE THREAD

**Issue by mahmoodn** [facebookincubator/BOLT#86]
I have added `--emit-relocs` in the linker option 
```
cc -o objs/nginx \
...
objs/ngx_modules.o \
-Wl,--emit-relocs -ldl -lpthread -lcrypt -lpcre -lz \
-Wl,-E
make[1]: Leaving directory '/home/mahmood/nginx-1.14.2-bolt'
```
But I don't see `.rela.text` in the ELF.
```
$ objdump -h ./nginx | grep rela
  8 .rela.dyn     00000060  0000000000409ae0  0000000000409ae0  00009ae0  2**3
  9 .rela.plt     00000d50  0000000000409b40  0000000000409b40  00009b40  2**3
```
Did I miss something?

**Comment by rafaelauler** [comment]
The command line looks correct, but I don't know which compiler is being invoked by "cc" so I can't really say if the driver is invoking the linker correctly, and which linker is handling it. Assuming gcc with binutils ld as the linker, you should be seeing .rela.text.

The next step here would be to make the driver dump the command line it is using to call the linker and make sure the linker is receiving either --emit-relocs or -q as a command line. That's all the linker needs to keep static relocations in the output file, if it supports it.

**Comment by xiaoxiao-luomu** [comment]
@ i have encountered the same problem, how you solove it ? very thanks

**Comment by xiaoxiao-luomu** [comment]
@mahmoodn  i have encountered the same problem, how you solove it ? very thanks

**Comment by mahmoodn** [comment]
@xiaoxiao-luomu What command do you use exactly? I actually don't remember since I at that time I was working with multiple options. Are you sure that you build a dynamic (and not a static) binary?
