### ISSUE TITLE
Increasing verbosity

### ISSUE THREAD

**Issue by mahmoodn** [facebookincubator/BOLT#89]
May I know how to increase the verbosity of BOLT? I see some messages like 

```
  DEBUG({
      dbgs() << "Launching perf: ";
      for (const char *Arg : Argv)
        dbgs() << Arg << " ";
      dbgs() << " 1> "
             << PPI.StdoutPath.data() << " 2> "
             << PPI.StderrPath.data() << "\n";
    });
```
How can I enable the debug then?

**Comment by rafaelauler** [comment]
This is an LLVM C++ dialect for debugging. You can print this by running BOLT with "-debug" or "-debug-only=<modulename>".  Example:
  llvm-bolt /bin/ls -o /tmp/foo -debug

For a module, say, dyld:
  llvm-bolt /bin/ls -o /tmp/foo -debug-only=dyld
