### ISSUE TITLE
Emitting relocation table when linking with dynamic libraries

### ISSUE THREAD

**Issue by petervbraun** [facebookincubator/BOLT#92]
I hope this is the right place to ask about the best way to set up for using BOLT. 
When linking with pthread and trying to emit relocs I get a fatal error. What would be the right way to approach this? Should I not emit relocs when linking with libpthread? Or is there some other solution?
I'm concerned that not using -r will limit the effectiveness of BOLT.

`/usr/bin/c++  -std=c++14 -fno-omit-frame-pointer  -Wall -Wextra -Wformat-security -Wvla -Wundef -Wmissing-format-attribute -Woverloaded-virtual -Wcast-qual -Wimplicit-fallthrough=2 -Wlogical-op -DDBUG_OFF -ffunction-sections -fdata-sections -O3 -DNDEBUG -r -fuse-ld=gold  CMakeFiles/uca9dump.dir/uca9-dump.cc.o
  -o ../runtime_output_directory/uca9dump -lpthread
/usr/bin/ld.gold: fatal error: cannot mix -r with dynamic object /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpthread.so
`

Specifically, I am trying to compile mysql-server with relocs so that I can apply BOLT.
If there is a better place to ask this, let me know.

Thanks!

**Comment by maksfb** [comment]
`-r` linker flag has a different meaning from `--emit-relocs`. The latter doesn't change the format of the output, it merely preserves relocation sections. Try to add `-Wl,--emit-relocs` to the compiler invocation.

**Comment by petervbraun** [comment]
thanks! This helps. I also had the additional problem that that the gnu gold linker did not work with these flags so I switched to llvm.

**Comment by xiaoxiao-luomu** [comment]
@maksfb, I use option -Wl, --emit-relocs to link program, but there is no section *.rela.text in the output .so, how to solve it ? my gcc --version is 5.4. hope for your answer, very thanks!

**Comment by maksfb** [comment]
How do you invoke the linker? If you run it directly, i.e. via `ld` command, then you need to drop `-Wl,` part and only pass `--emit-relocs`.

**Comment by xiaoxiao-luomu** [comment]
@maksfb set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -Wl,--build-id=none -Wl,--emit-relocs") 
I write the linker option in the CMakeLists.txt. By the way, the generated *.so is loaded dynamically when my program is running.

**Comment by maksfb** [comment]
That's the cmake variable that will get propagated to the actual linker command or maybe not. Can you do a verbose build and look if the flag is passed to the command that produces the binary you are trying to optimize?

**Comment by xiaoxiao-luomu** [comment]
@maksfb I add the compile option --verbose and see that --emit-rerlocs is passed to the linker, but *rela.text is also not found in *.so files.  it is confusing.

**Comment by maksfb** [comment]
This means that either relocations were not saved by the linker or they were removed by a post-processing step (e.g. running `strip` or `objcopy` on the binary). What is the linker you are using? If you can narrow down the problem to the linker, it will be good to file a bug against it. Is there anyway to reproduce your build process?

**Comment by xiaoxiao-luomu** [comment]
@maksfb very thanks！--emit-relocs works after I removed strip. Bolt also works.
But another problem comes, the bolt processed .so file is bigger 10 times than the original .so, how to simplify the so ? 
is ok to use --strip-all for the processed .so file ?

**Comment by xiaoxiao-luomu** [comment]
@maksfb after bolt optimization，no effect，even a little decline，too sad.

**Comment by maksfb** [comment]
What's the output of BOLT? Add `-dyno-stats` option to get more details. Perhaps your .so performance is not front-end bound.

**Comment by xiaoxiao-luomu** [comment]
@maksfb the compile options in my project are:	
        -g
	-fno-builtin
	-fno-omit-frame-pointer
	-lstdc++
	-fno-strict-aliasing 
	-fno-inline-small-functions 
	-fPIC
	-funroll-loops
	-funswitch-loops
	-fstack-protector-strong
       -m64
COMMAND objcopy --only-keep-debug ${TARGET_FILE} ${SYMBOL_FILE}
COMMAND objcopy --add-gnu-debuglink=${SYMBOL_FILE} ${TARGET_FILE}

what's problem with it ? thanks very much
